/* istanbul ignore file */

/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-core' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    skyux_numeric_billions_symbol: { message: 'B' },
    skyux_numeric_millions_symbol: { message: 'M' },
    skyux_numeric_thousands_symbol: { message: 'K' },
    skyux_numeric_trillions_symbol: { message: 'T' },
  },
  'FR-CA': {
    skyux_numeric_billions_symbol: { message: 'G' },
    skyux_numeric_millions_symbol: { message: 'M' },
    skyux_numeric_thousands_symbol: { message: 'K' },
    skyux_numeric_trillions_symbol: { message: 'T' },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyCoreResourcesModule {}
