/* istanbul ignore file */

/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-inline-form' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    skyux_inline_form_button_cancel: { message: 'Cancel' },
    skyux_inline_form_button_delete: { message: 'Delete' },
    skyux_inline_form_button_done: { message: 'Done' },
    skyux_inline_form_button_save: { message: 'Save' },
  },
  'FR-CA': {
    skyux_inline_form_button_cancel: { message: 'Annuler' },
    skyux_inline_form_button_delete: { message: 'Supprimer' },
    skyux_inline_form_button_done: { message: 'Terminé' },
    skyux_inline_form_button_save: { message: 'Sauvegarder' },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyInlineFormResourcesModule {}
