/* istanbul ignore file */

/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-phone-field' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    skyux_phone_field_country_search_dismiss: {
      message: 'Dismiss country search',
    },
    skyux_phone_field_country_search_label: {
      message: 'Dismiss country search',
    },
    skyux_phone_field_country_search_placeholder: {
      message: 'Search for a country',
    },
    skyux_phone_field_country_select_label: { message: 'Choose country.' },
    skyux_phone_field_country_selected_label: {
      message: '{0} is currently selected.',
    },
    skyux_phone_field_format_hint_text: { message: 'Example: {0}.' },
  },
  'FR-CA': {
    skyux_phone_field_country_search_dismiss: {
      message: 'Omettre la recherche du pays',
    },
    skyux_phone_field_country_search_label: {
      message: 'Omettre la recherche du pays',
    },
    skyux_phone_field_country_search_placeholder: {
      message: 'Rechercher un pays',
    },
    skyux_phone_field_country_select_label: { message: 'Choisissez un pays.' },
    skyux_phone_field_country_selected_label: {
      message: '{0} est actuellement sélectionné.',
    },
    skyux_phone_field_format_hint_text: { message: 'Exemple : {0}.' },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyPhoneFieldResourcesModule {}
