/* istanbul ignore file */
/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-filter-bar' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    skyux_filter_bar_clear_filters_confirm_apply_label: {
      message: 'Clear values',
    },
    skyux_filter_bar_clear_filters_confirm_body: {
      message:
        'This will not remove any filters, but any values you have set will be removed.',
    },
    skyux_filter_bar_clear_filters_confirm_cancel_label: { message: 'Cancel' },
    skyux_filter_bar_clear_filters_confirm_title: {
      message:
        'Are you sure you want to reset all filters to their original values?',
    },
    skyux_filter_bar_clear_filters_label: { message: 'Clear all values' },
    skyux_filter_bar_filter_label: { message: 'Filters' },
    skyux_filter_bar_filter_picker_descriptor: { message: 'filters' },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyFilterBarResourcesModule {}
