/**
 *
 * AUTO-GENERATED FILE, DO NOT MODIFY
 *
 * This file is generated by the code-examples prebuild step. It can be regenerated manually using the command:
 *
 * # npx nx run code-examples:prebuild
 *
 */
import { Routes } from '@angular/router';

export const routes: Routes = [
  {
    path: 'ActionBarsSummaryActionBarBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ActionBarsSummaryActionBarBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ActionBarsSummaryActionBarErrorExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ActionBarsSummaryActionBarErrorExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ActionBarsSummaryActionBarModalExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ActionBarsSummaryActionBarModalExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ActionBarsSummaryActionBarTabExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ActionBarsSummaryActionBarTabExampleComponent: c }) => c,
      ),
  },
  {
    path: 'AgGridDataEntryGridBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ AgGridDataEntryGridBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'AgGridDataEntryGridDataManagerAddedExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ AgGridDataEntryGridDataManagerAddedExampleComponent: c }) => c,
      ),
  },
  {
    path: 'AgGridDataEntryGridFocusExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ AgGridDataEntryGridFocusExampleComponent: c }) => c,
      ),
  },
  {
    path: 'AgGridDataEntryGridInlineHelpExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ AgGridDataEntryGridInlineHelpExampleComponent: c }) => c,
      ),
  },
  {
    path: 'AgGridDataGridBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ AgGridDataGridBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'AgGridDataGridBasicMultiselectExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ AgGridDataGridBasicMultiselectExampleComponent: c }) => c,
      ),
  },
  {
    path: 'AgGridDataGridDataManagerExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ AgGridDataGridDataManagerExampleComponent: c }) => c,
      ),
  },
  {
    path: 'AgGridDataGridDataManagerMultiselectExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ AgGridDataGridDataManagerMultiselectExampleComponent: c }) => c,
      ),
  },
  {
    path: 'AgGridDataGridInlineHelpExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ AgGridDataGridInlineHelpExampleComponent: c }) => c,
      ),
  },
  {
    path: 'AgGridDataGridPagingExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ AgGridDataGridPagingExampleComponent: c }) => c,
      ),
  },
  {
    path: 'AgGridDataGridTemplateRefColumnExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ AgGridDataGridTemplateRefColumnExampleComponent: c }) => c,
      ),
  },
  {
    path: 'AgGridDataGridTopScrollExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ AgGridDataGridTopScrollExampleComponent: c }) => c,
      ),
  },
  {
    path: 'AngularTreeComponentAngularTreeBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ AngularTreeComponentAngularTreeBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'AngularTreeComponentAngularTreeHelpKeyExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ AngularTreeComponentAngularTreeHelpKeyExampleComponent: c }) => c,
      ),
  },
  {
    path: 'AngularTreeComponentAngularTreePreselectedNodesExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({
          AngularTreeComponentAngularTreePreselectedNodesExampleComponent: c,
        }) => c,
      ),
  },
  {
    path: 'AutonumericCurrencyExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ AutonumericCurrencyExampleComponent: c }) => c,
      ),
  },
  {
    path: 'AutonumericInternationalFormattingExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ AutonumericInternationalFormattingExampleComponent: c }) => c,
      ),
  },
  {
    path: 'AutonumericOptionsProviderExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ AutonumericOptionsProviderExampleComponent: c }) => c,
      ),
  },
  {
    path: 'AutonumericPresetExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ AutonumericPresetExampleComponent: c }) => c,
      ),
  },
  {
    path: 'AvatarExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(({ AvatarExampleComponent: c }) => c),
  },
  {
    path: 'ColorpickerBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ColorpickerBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ColorpickerHelpKeyExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ColorpickerHelpKeyExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ColorpickerProgrammaticExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ColorpickerProgrammaticExampleComponent: c }) => c,
      ),
  },
  {
    path: 'CoreIdExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(({ CoreIdExampleComponent: c }) => c),
  },
  {
    path: 'CoreMediaQueryBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ CoreMediaQueryBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'CoreMediaQueryResponsiveHostExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ CoreMediaQueryResponsiveHostExampleComponent: c }) => c,
      ),
  },
  {
    path: 'CoreNumericBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ CoreNumericBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'DataManagerBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ DataManagerBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'DatetimeDatepickerBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ DatetimeDatepickerBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'DatetimeDatepickerCustomDatesExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ DatetimeDatepickerCustomDatesExampleComponent: c }) => c,
      ),
  },
  {
    path: 'DatetimeDatepickerFuzzyExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ DatetimeDatepickerFuzzyExampleComponent: c }) => c,
      ),
  },
  {
    path: 'DatetimeDatePipeBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ DatetimeDatePipeBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'DatetimeDateRangePickerBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ DatetimeDateRangePickerBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'DatetimeDateRangePickerCustomCalculatorExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ DatetimeDateRangePickerCustomCalculatorExampleComponent: c }) => c,
      ),
  },
  {
    path: 'DatetimeDateRangePickerHelpKeyExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ DatetimeDateRangePickerHelpKeyExampleComponent: c }) => c,
      ),
  },
  {
    path: 'DatetimeTimepickerBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ DatetimeTimepickerBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ErrorsErrorEmbeddedExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ErrorsErrorEmbeddedExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ErrorsErrorModalExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ErrorsErrorModalExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FilterBarLookupExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FilterBarLookupExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FilterBarModalExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FilterBarModalExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FilterBarSelectableExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FilterBarSelectableExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FlyoutBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FlyoutBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FlyoutCustomHeadersExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FlyoutCustomHeadersExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FormsCharacterCountExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FormsCharacterCountExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FormsCheckboxBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FormsCheckboxBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FormsCheckboxHelpKeyExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FormsCheckboxHelpKeyExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FormsCheckboxIconGroupExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FormsCheckboxIconGroupExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FormsFieldGroupBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FormsFieldGroupBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FormsFieldGroupHelpKeyExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FormsFieldGroupHelpKeyExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FormsFileAttachmentBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FormsFileAttachmentBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FormsFileAttachmentHelpKeyExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FormsFileAttachmentHelpKeyExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FormsFileDropBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FormsFileDropBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FormsFileDropHelpKeyExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FormsFileDropHelpKeyExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FormsInputBoxBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FormsInputBoxBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FormsInputBoxWithCustomFormErrorsExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FormsInputBoxWithCustomFormErrorsExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FormsRadioHelpKeyExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FormsRadioHelpKeyExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FormsRadioIconExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FormsRadioIconExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FormsRadioStandardExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FormsRadioStandardExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FormsSelectionBoxCheckboxExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FormsSelectionBoxCheckboxExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FormsSelectionBoxRadioExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FormsSelectionBoxRadioExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FormsToggleSwitchBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FormsToggleSwitchBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'FormsToggleSwitchHelpKeyExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ FormsToggleSwitchHelpKeyExampleComponent: c }) => c,
      ),
  },
  {
    path: 'HelpInlineActionClickExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ HelpInlineActionClickExampleComponent: c }) => c,
      ),
  },
  {
    path: 'HelpInlineHelpKeyExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ HelpInlineHelpKeyExampleComponent: c }) => c,
      ),
  },
  {
    path: 'HelpInlinePopoverExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ HelpInlinePopoverExampleComponent: c }) => c,
      ),
  },
  {
    path: 'IconBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ IconBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'IconIconButtonExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ IconIconButtonExampleComponent: c }) => c,
      ),
  },
  {
    path: 'IndicatorsAlertBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ IndicatorsAlertBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'IndicatorsIllustrationBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ IndicatorsIllustrationBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'IndicatorsKeyInfoBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ IndicatorsKeyInfoBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'IndicatorsKeyInfoHelpKeyExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ IndicatorsKeyInfoHelpKeyExampleComponent: c }) => c,
      ),
  },
  {
    path: 'IndicatorsLabelBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ IndicatorsLabelBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'IndicatorsStatusIndicatorBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ IndicatorsStatusIndicatorBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'IndicatorsStatusIndicatorHelpKeyExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ IndicatorsStatusIndicatorHelpKeyExampleComponent: c }) => c,
      ),
  },
  {
    path: 'IndicatorsTextHighlightBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ IndicatorsTextHighlightBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'IndicatorsTokensBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ IndicatorsTokensBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'IndicatorsTokensCustomExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ IndicatorsTokensCustomExampleComponent: c }) => c,
      ),
  },
  {
    path: 'IndicatorsWaitElementExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ IndicatorsWaitElementExampleComponent: c }) => c,
      ),
  },
  {
    path: 'IndicatorsWaitPageExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ IndicatorsWaitPageExampleComponent: c }) => c,
      ),
  },
  {
    path: 'InlineFormBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ InlineFormBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'InlineFormCustomButtonsExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ InlineFormCustomButtonsExampleComponent: c }) => c,
      ),
  },
  {
    path: 'InlineFormRepeatersExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ InlineFormRepeatersExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutActionButtonBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutActionButtonBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutActionButtonPermalinkExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutActionButtonPermalinkExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutBackToTopInfiniteScrollExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutBackToTopInfiniteScrollExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutBackToTopRepeaterExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutBackToTopRepeaterExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutBoxBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutBoxBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutBoxHelpKeyExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutBoxHelpKeyExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutCardBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutCardBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutDefinitionListBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutDefinitionListBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutDescriptionListHelpKeyExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutDescriptionListHelpKeyExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutDescriptionListHorizontalExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutDescriptionListHorizontalExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutDescriptionListInlineHelpExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutDescriptionListInlineHelpExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutDescriptionListLongDescriptionExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutDescriptionListLongDescriptionExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutDescriptionListVerticalExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutDescriptionListVerticalExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutFluidGridExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutFluidGridExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutFormatExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutFormatExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutInlineDeleteCustomExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutInlineDeleteCustomExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutInlineDeleteRepeaterExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutInlineDeleteRepeaterExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutPageSummaryBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutPageSummaryBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutTextExpandInlineExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutTextExpandInlineExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutTextExpandModalExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutTextExpandModalExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutTextExpandNewlineExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutTextExpandNewlineExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutTextExpandRepeaterExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutTextExpandRepeaterExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutToolbarBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutToolbarBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LayoutToolbarSectionedExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LayoutToolbarSectionedExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ListsFilterInlineExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ListsFilterInlineExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ListsFilterModalExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ListsFilterModalExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ListsInfiniteScrollRepeaterExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ListsInfiniteScrollRepeaterExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ListsListSummaryBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ListsListSummaryBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ListsPagingBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ListsPagingBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ListsPagingWithContentExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ListsPagingWithContentExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ListsRepeaterAddRemoveExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ListsRepeaterAddRemoveExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ListsRepeaterBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ListsRepeaterBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ListsRepeaterInlineFormExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ListsRepeaterInlineFormExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ListsSortBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ListsSortBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LookupAddItemExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LookupAddItemExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LookupAutocompleteAdvancedExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LookupAutocompleteAdvancedExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LookupAutocompleteAnyValueExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LookupAutocompleteAnyValueExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LookupAutocompleteBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LookupAutocompleteBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LookupAutocompleteCustomSearchExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LookupAutocompleteCustomSearchExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LookupAutocompleteSearchFiltersExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LookupAutocompleteSearchFiltersExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LookupCountryFieldBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LookupCountryFieldBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LookupCustomPickerExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LookupCustomPickerExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LookupMultiSelectExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LookupMultiSelectExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LookupResultTemplatesExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LookupResultTemplatesExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LookupSearchBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LookupSearchBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LookupSelectionModalAddItemExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LookupSelectionModalAddItemExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LookupSelectionModalBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LookupSelectionModalBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'LookupSingleSelectExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ LookupSingleSelectExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ModalsConfirmBasicWithControllerExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ModalsConfirmBasicWithControllerExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ModalsConfirmBasicWithHarnessExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ModalsConfirmBasicWithHarnessExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ModalsModalBasicWithControllerExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ModalsModalBasicWithControllerExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ModalsModalBasicWithHarnessExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ModalsModalBasicWithHarnessExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ModalsModalBasicWithHarnessHelpKeyExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ModalsModalBasicWithHarnessHelpKeyExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ModalsModalWithErrorExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ModalsModalWithErrorExampleComponent: c }) => c,
      ),
  },
  {
    path: 'NavbarExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(({ NavbarExampleComponent: c }) => c),
  },
  {
    path: 'PagesActionHubExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ PagesActionHubExampleComponent: c }) => c,
      ),
  },
  {
    path: 'PagesPageDataManagerSplitViewFitLayoutExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ PagesPageDataManagerSplitViewFitLayoutExampleComponent: c }) => c,
      ),
  },
  {
    path: 'PagesPageHomePageBlocksLayoutExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ PagesPageHomePageBlocksLayoutExampleComponent: c }) => c,
      ),
  },
  {
    path: 'PagesPageListPageListLayoutExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ PagesPageListPageListLayoutExampleComponent: c }) => c,
      ),
  },
  {
    path: 'PagesPageListPageTabsLayoutExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ PagesPageListPageTabsLayoutExampleComponent: c }) => c,
      ),
  },
  {
    path: 'PagesPageRecordPageBlocksLayoutExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ PagesPageRecordPageBlocksLayoutExampleComponent: c }) => c,
      ),
  },
  {
    path: 'PagesPageRecordPageTabsLayoutExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ PagesPageRecordPageTabsLayoutExampleComponent: c }) => c,
      ),
  },
  {
    path: 'PagesPageSplitViewPageFitLayoutExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ PagesPageSplitViewPageFitLayoutExampleComponent: c }) => c,
      ),
  },
  {
    path: 'PhoneFieldBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ PhoneFieldBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'PopoversDropdownBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ PopoversDropdownBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'PopoversPopoverBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ PopoversPopoverBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'PopoversPopoverProgrammaticExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ PopoversPopoverProgrammaticExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ProgressIndicatorPassiveIndicatorBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ProgressIndicatorPassiveIndicatorBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ProgressIndicatorWaterfallIndicatorBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ProgressIndicatorWaterfallIndicatorBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ProgressIndicatorWizardBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ProgressIndicatorWizardBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'RouterHrefBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ RouterHrefBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'SplitViewBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ SplitViewBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'SplitViewPageBoundExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ SplitViewPageBoundExampleComponent: c }) => c,
      ),
  },
  {
    path: 'TabsDynamicAddCloseExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ TabsDynamicAddCloseExampleComponent: c }) => c,
      ),
  },
  {
    path: 'TabsDynamicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ TabsDynamicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'TabsSectionedFormModalExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ TabsSectionedFormModalExampleComponent: c }) => c,
      ),
  },
  {
    path: 'TabsStaticAddCloseExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ TabsStaticAddCloseExampleComponent: c }) => c,
      ),
  },
  {
    path: 'TabsStaticExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ TabsStaticExampleComponent: c }) => c,
      ),
  },
  {
    path: 'TabsVerticalTabsBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ TabsVerticalTabsBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'TabsVerticalTabsGroupedExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ TabsVerticalTabsGroupedExampleComponent: c }) => c,
      ),
  },
  {
    path: 'TabsVerticalTabsMixedExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ TabsVerticalTabsMixedExampleComponent: c }) => c,
      ),
  },
  {
    path: 'TabsWizardBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ TabsWizardBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'TextEditorExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ TextEditorExampleComponent: c }) => c,
      ),
  },
  {
    path: 'TextEditorHelpKeyExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ TextEditorHelpKeyExampleComponent: c }) => c,
      ),
  },
  {
    path: 'TextEditorRichTextDisplayExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ TextEditorRichTextDisplayExampleComponent: c }) => c,
      ),
  },
  {
    path: 'TilesBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ TilesBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ToastBasicExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ToastBasicExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ToastCustomComponentExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ToastCustomComponentExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ValidationEmailValidationControlValidatorExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ValidationEmailValidationControlValidatorExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ValidationEmailValidationDirectiveExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ValidationEmailValidationDirectiveExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ValidationUrlValidationControlValidatorExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ValidationUrlValidationControlValidatorExampleComponent: c }) => c,
      ),
  },
  {
    path: 'ValidationUrlValidationDirectiveExampleComponent',
    loadComponent: () =>
      import('@skyux/code-examples').then(
        ({ ValidationUrlValidationDirectiveExampleComponent: c }) => c,
      ),
  },
];
export default routes;
