/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module modules/shared/sky-angular-tree-component' schematic.
 * To update this file, simply rerun the command.
 */

import { NgModule } from '@angular/core';
import {
  getLibStringForLocale,
  SkyAppLocaleInfo,
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesProvider,
  SKY_LIB_RESOURCES_PROVIDERS
} from '@skyux/i18n';

const RESOURCES: { [locale: string]: SkyLibResources } = {
  'EN-US': {"skyux_angular_tree_clear_all":{"message":"Clear all"},"skyux_angular_tree_click_to_expand":{"message":"Click to expand"},"skyux_angular_tree_collapse_all":{"message":"Collapse"},"skyux_angular_tree_expand_all":{"message":"Expand"},"skyux_angular_tree_select_all":{"message":"Select all"}},
};

export class SkyAngularTreeComponentResourcesProvider implements SkyLibResourcesProvider {
  public getString(localeInfo: SkyAppLocaleInfo, name: string): string {
    return getLibStringForLocale(RESOURCES, localeInfo.locale, name);
  }
}

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
  providers: [{
    provide: SKY_LIB_RESOURCES_PROVIDERS,
    useClass: SkyAngularTreeComponentResourcesProvider,
    multi: true
  }]
})
export class SkyAngularTreeComponentResourcesModule { }
