/* istanbul ignore file */

/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-layout' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    skyux_back_to_top: { message: 'Back to top' },
    skyux_card_checkbox_label: { message: 'Select card' },
    skyux_definition_list_none_found: { message: 'None found.' },
    skyux_description_list_none_found: { message: 'None found.' },
    skyux_inline_delete_assistive_text: {
      message: 'Are you sure you want to delete this item?',
    },
    skyux_inline_delete_cancel: { message: 'Cancel' },
    skyux_inline_delete_confirm_deletion: { message: 'Confirm deletion' },
    skyux_inline_delete_delete: { message: 'Delete' },
    skyux_text_expand_close_text: { message: 'Close' },
    skyux_text_expand_modal_title: { message: 'Expanded view' },
    skyux_text_expand_see_less: { message: 'See less' },
    skyux_text_expand_see_more: { message: 'See more' },
  },
  'FR-CA': {
    skyux_back_to_top: { message: 'Retour en haut' },
    skyux_card_checkbox_label: { message: 'Sélectionner la carte' },
    skyux_definition_list_none_found: { message: 'Aucun trouvé.' },
    skyux_description_list_none_found: { message: 'Aucun trouvé.' },
    skyux_inline_delete_assistive_text: {
      message: 'Êtes-vous certain de vouloir supprimer cet élément?',
    },
    skyux_inline_delete_cancel: { message: 'Annuler' },
    skyux_inline_delete_confirm_deletion: {
      message: 'Confirmer la suppression',
    },
    skyux_inline_delete_delete: { message: 'Supprimer' },
    skyux_text_expand_close_text: { message: 'Fermer' },
    skyux_text_expand_modal_title: { message: 'Vue agrandie' },
    skyux_text_expand_see_less: { message: 'Voir moins' },
    skyux_text_expand_see_more: { message: 'Voir plus' },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyLayoutResourcesModule {}
