// This file is auto-generated by running:
// # nx g @skyux-sdk/e2e-schematics:storybook-composition
//
import type { StorybookConfig } from '@storybook/angular';

import { rootMain } from '../../../../.storybook/main';

const config: StorybookConfig = {
  ...rootMain,
  // There needs to be one local story in order for composition to work.
  stories: [
    ...rootMain.stories,
    '../src/lib/**/*.stories.mdx',
    '../src/lib/**/*.stories.@(js|jsx|ts|tsx)',
  ],
  framework: {
    name: '@storybook/angular',
    options: {},
  },
  docs: {
    autodocs: true,
  },
};
module.exports = config;
