// This file is auto-generated by running:
// # nx g @skyux-sdk/e2e-schematics:storybook-composition
//
import type { StorybookConfig } from 'storybook/internal/types';

// eslint-disable-next-line @nx/enforce-module-boundaries
import { rootMain } from '../../../../.storybook/main';

const config: StorybookConfig = {
  ...rootMain,
  // There needs to be one local story in order for composition to work.
  stories: ['../src/lib/**/*.stories.@(js|ts)'],
};
export default config;
