// This file is auto-generated by running:
// # nx g @skyux-sdk/e2e-schematics:storybook-composition
//
import type { StorybookConfig } from '@storybook/core-common';

import { rootMain } from '../../../../.storybook/main';

const config: StorybookConfig = {
  ...rootMain,

  // There needs to be one local story in order for composition to work.
  stories: [
    ...rootMain.stories,
    '../src/lib/**/*.stories.mdx',
    '../src/lib/**/*.stories.@(js|jsx|ts|tsx)',
  ],
};

module.exports = config;
