/* istanbul ignore file */
/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-errors' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    skyux_errors_broken_description: {
      message: 'Something went wrong.\nTry again or come back later.',
    },
    skyux_errors_broken_title: { message: "That's odd..." },
    skyux_errors_construction_description: {
      message: 'We appreciate your patience while we\nmake improvements.',
    },
    skyux_errors_construction_title: { message: 'Work in progress.' },
    skyux_errors_not_found_description: {
      message: 'Pardon us, but this page\nis missing or has moved.',
    },
    skyux_errors_not_found_title: { message: 'Nothing to see here.' },
    skyux_errors_security_description: {
      message: 'Ask your administrator for access.',
    },
    skyux_errors_security_title: {
      message: "Heads up!\nYou're in a restricted area.",
    },
  },
  'FR-CA': {
    skyux_errors_broken_description: {
      message:
        'Un problème est survenu.\nEssayez à nouveau ou revenez plus tard.',
    },
    skyux_errors_broken_title: { message: 'C’est curieux…' },
    skyux_errors_construction_description: {
      message:
        'Nous apprécions votre patience pendant que \nnous apportons des améliorations.',
    },
    skyux_errors_construction_title: { message: 'Travaux en cours.' },
    skyux_errors_not_found_description: {
      message:
        'Nous sommes désolés, mais cette page \nest manquante ou a été déplacée.',
    },
    skyux_errors_not_found_title: { message: 'Il n’y a rien à voir ici.' },
    skyux_errors_security_description: {
      message: 'Demandez à votre administrateur de vous accorder l’accès.',
    },
    skyux_errors_security_title: {
      message: 'Attention!\nVous êtes dans une zone restreinte.',
    },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyErrorsResourcesModule {}
