/* istanbul ignore file */

/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-datetime' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-AU': {
    skyux_date_range_picker_format_label_last_fiscal_year: {
      message: 'Last financial year',
    },
    skyux_date_range_picker_format_label_this_fiscal_year: {
      message: 'This financial year',
    },
    skyux_date_range_picker_format_label_next_fiscal_year: {
      message: 'Next financial year',
    },
  },
  'EN-GB': {
    skyux_date_range_picker_format_label_last_fiscal_year: {
      message: 'Last financial year',
    },
    skyux_date_range_picker_format_label_this_fiscal_year: {
      message: 'This financial year',
    },
    skyux_date_range_picker_format_label_next_fiscal_year: {
      message: 'Next financial year',
    },
  },
  'EN-NZ': {
    skyux_date_range_picker_format_label_last_fiscal_year: {
      message: 'Last financial year',
    },
    skyux_date_range_picker_format_label_this_fiscal_year: {
      message: 'This financial year',
    },
    skyux_date_range_picker_format_label_next_fiscal_year: {
      message: 'Next financial year',
    },
  },
  'EN-US': {
    skyux_datepicker_format_hint_text: { message: 'Use the format {0}.' },
    skyux_datepicker_trigger_button_label: { message: 'Select date' },
    skyux_datepicker_trigger_button_label_context: {
      message: 'Open calendar for {0}',
    },
    skyux_datepicker_move_calendar_previous_day: { message: 'Previous month' },
    skyux_datepicker_move_calendar_next_day: { message: 'Next month' },
    skyux_datepicker_move_calendar_previous_month: { message: 'Previous year' },
    skyux_datepicker_move_calendar_next_month: { message: 'Next year' },
    skyux_datepicker_move_calendar_previous_year: { message: 'Previous page' },
    skyux_datepicker_move_calendar_next_year: { message: 'Next page' },
    skyux_timepicker_button_label: { message: 'Choose time' },
    skyux_timepicker_button_label_context: {
      message: 'Open time picker for {0}',
    },
    skyux_timepicker_close: { message: 'Done' },
    skyux_date_range_picker_default_label: { message: 'Select a date range' },
    skyux_date_range_picker_end_date_before_start_date_error_label_text: {
      message:
        'Change the date range so that the end date is before the start date.',
    },
    skyux_date_range_picker_format_label_specific_range: {
      message: 'Specific range',
    },
    skyux_date_range_picker_format_label_before: { message: 'Before' },
    skyux_date_range_picker_format_label_after: { message: 'After' },
    skyux_date_range_picker_format_label_any_time: { message: 'At any time' },
    skyux_date_range_picker_format_label_yesterday: { message: 'Yesterday' },
    skyux_date_range_picker_format_label_today: { message: 'Today' },
    skyux_date_range_picker_format_label_tomorrow: { message: 'Tomorrow' },
    skyux_date_range_picker_format_label_last_week: { message: 'Last week' },
    skyux_date_range_picker_format_label_this_week: { message: 'This week' },
    skyux_date_range_picker_format_label_next_week: { message: 'Next week' },
    skyux_date_range_picker_format_label_last_month: { message: 'Last month' },
    skyux_date_range_picker_format_label_this_month: { message: 'This month' },
    skyux_date_range_picker_format_label_next_month: { message: 'Next month' },
    skyux_date_range_picker_format_label_last_quarter: {
      message: 'Last quarter',
    },
    skyux_date_range_picker_format_label_this_quarter: {
      message: 'This quarter',
    },
    skyux_date_range_picker_format_label_next_quarter: {
      message: 'Next quarter',
    },
    skyux_date_range_picker_format_label_last_calendar_year: {
      message: 'Last calendar year',
    },
    skyux_date_range_picker_format_label_this_calendar_year: {
      message: 'This calendar year',
    },
    skyux_date_range_picker_format_label_next_calendar_year: {
      message: 'Next calendar year',
    },
    skyux_date_range_picker_format_label_last_fiscal_year: {
      message: 'Last fiscal year',
    },
    skyux_date_range_picker_format_label_this_fiscal_year: {
      message: 'This fiscal year',
    },
    skyux_date_range_picker_format_label_next_fiscal_year: {
      message: 'Next fiscal year',
    },
    skyux_date_range_picker_start_date_label: { message: 'From date' },
    skyux_date_range_picker_end_date_label: { message: 'To date' },
    skyux_date_range_picker_before_date_label: { message: 'Before date' },
    skyux_date_range_picker_after_date_label: { message: 'After date' },
    skyux_date_range_picker_default_aria_label: { message: '{0} for {1}' },
  },
  ES: {
    skyux_datepicker_format_hint_text: { message: 'Utilice el formato {0}.' },
    skyux_datepicker_trigger_button_label: { message: 'Seleccionar fecha' },
    skyux_datepicker_trigger_button_label_context: {
      message: 'Abrir el calendario para {0}',
    },
    skyux_datepicker_move_calendar_previous_day: { message: 'Mes anterior' },
    skyux_datepicker_move_calendar_next_day: { message: 'Próximo mes' },
    skyux_datepicker_move_calendar_previous_month: { message: 'Año anterior' },
    skyux_datepicker_move_calendar_next_month: { message: 'Próximo año' },
    skyux_datepicker_move_calendar_previous_year: {
      message: 'Página anterior',
    },
    skyux_datepicker_move_calendar_next_year: { message: 'Página siguiente' },
    skyux_timepicker_button_label: { message: 'Elegir hora' },
    skyux_timepicker_button_label_context: {
      message: 'Abrir el selector de hora para {0}',
    },
    skyux_timepicker_close: { message: 'Hecho' },
    skyux_date_range_picker_default_label: {
      message: 'Seleccionar un rango de fechas',
    },
    skyux_date_range_picker_end_date_before_start_date_error_label_text: {
      message:
        'Cambie el rango de fechas para que la fecha de finalización sea posterior a la fecha de inicio.',
    },
    skyux_date_range_picker_format_label_specific_range: {
      message: 'Rango específico',
    },
    skyux_date_range_picker_format_label_before: { message: 'Antes de' },
    skyux_date_range_picker_format_label_after: { message: 'Después de' },
    skyux_date_range_picker_format_label_any_time: {
      message: 'En cualquier momento',
    },
    skyux_date_range_picker_format_label_yesterday: { message: 'Ayer' },
    skyux_date_range_picker_format_label_today: { message: 'Hoy' },
    skyux_date_range_picker_format_label_tomorrow: { message: 'Mañana' },
    skyux_date_range_picker_format_label_last_week: {
      message: 'Semana pasada',
    },
    skyux_date_range_picker_format_label_this_week: { message: 'Esta semana' },
    skyux_date_range_picker_format_label_next_week: {
      message: 'Próxima semana',
    },
    skyux_date_range_picker_format_label_last_month: { message: 'Mes pasado' },
    skyux_date_range_picker_format_label_this_month: { message: 'Este mes' },
    skyux_date_range_picker_format_label_next_month: { message: 'Mes próximo' },
    skyux_date_range_picker_format_label_last_quarter: {
      message: 'Trimestre pasado',
    },
    skyux_date_range_picker_format_label_this_quarter: {
      message: 'Este trimestre',
    },
    skyux_date_range_picker_format_label_next_quarter: {
      message: 'Próximo trimestre',
    },
    skyux_date_range_picker_format_label_last_calendar_year: {
      message: 'Último año natural',
    },
    skyux_date_range_picker_format_label_this_calendar_year: {
      message: 'Este año natural',
    },
    skyux_date_range_picker_format_label_next_calendar_year: {
      message: 'Próximo año natural',
    },
    skyux_date_range_picker_format_label_last_fiscal_year: {
      message: 'Último año fiscal',
    },
    skyux_date_range_picker_format_label_this_fiscal_year: {
      message: 'Este año fiscal',
    },
    skyux_date_range_picker_format_label_next_fiscal_year: {
      message: 'Próximo año fiscal',
    },
    skyux_date_range_picker_start_date_label: { message: 'Desde fecha' },
    skyux_date_range_picker_end_date_label: { message: 'Hasta fecha' },
    skyux_date_range_picker_before_date_label: { message: 'Fecha anterior a' },
    skyux_date_range_picker_after_date_label: { message: 'Fecha posterior a' },
    skyux_date_range_picker_default_aria_label: { message: '{0} para {1}' },
  },
  'FR-CA': {
    skyux_datepicker_format_hint_text: { message: 'Utilisez le format {0}.' },
    skyux_datepicker_trigger_button_label: { message: 'Sélectionner la date' },
    skyux_datepicker_trigger_button_label_context: {
      message: 'Ouvrir le calendrier pour {0}',
    },
    skyux_datepicker_move_calendar_previous_day: { message: 'Mois précédent' },
    skyux_datepicker_move_calendar_next_day: { message: 'Le mois prochain' },
    skyux_datepicker_move_calendar_previous_month: {
      message: 'Année précédente',
    },
    skyux_datepicker_move_calendar_next_month: { message: 'Année suivante' },
    skyux_datepicker_move_calendar_previous_year: {
      message: 'Page précédente',
    },
    skyux_datepicker_move_calendar_next_year: { message: 'Page suivante' },
    skyux_timepicker_button_label: { message: 'Choisir l’heure' },
    skyux_timepicker_button_label_context: {
      message: 'Ouvrir le sélecteur d’heure pour {0}',
    },
    skyux_timepicker_close: { message: 'Terminé' },
    skyux_date_range_picker_default_label: {
      message: 'Sélectionner une plage de dates',
    },
    skyux_date_range_picker_end_date_before_start_date_error_label_text: {
      message:
        'Modifiez la plage de date de façon à ce que la date de fin soit avant la date de début.',
    },
    skyux_date_range_picker_format_label_specific_range: {
      message: 'Plage spécifique',
    },
    skyux_date_range_picker_format_label_before: { message: 'Avant' },
    skyux_date_range_picker_format_label_after: { message: 'Après' },
    skyux_date_range_picker_format_label_any_time: {
      message: 'N’importe quand',
    },
    skyux_date_range_picker_format_label_yesterday: { message: 'Hier' },
    skyux_date_range_picker_format_label_today: { message: 'Aujourd’hui' },
    skyux_date_range_picker_format_label_tomorrow: { message: 'Demain' },
    skyux_date_range_picker_format_label_last_week: {
      message: 'La semaine dernière',
    },
    skyux_date_range_picker_format_label_this_week: {
      message: 'Cette semaine',
    },
    skyux_date_range_picker_format_label_next_week: {
      message: 'La semaine prochaine',
    },
    skyux_date_range_picker_format_label_last_month: {
      message: 'Le mois dernier',
    },
    skyux_date_range_picker_format_label_this_month: { message: 'Ce mois-ci' },
    skyux_date_range_picker_format_label_next_month: {
      message: 'Le mois prochain',
    },
    skyux_date_range_picker_format_label_last_quarter: {
      message: 'Le trimestre dernier',
    },
    skyux_date_range_picker_format_label_this_quarter: {
      message: 'Ce trimestre',
    },
    skyux_date_range_picker_format_label_next_quarter: {
      message: 'Le trimestre prochain',
    },
    skyux_date_range_picker_format_label_last_calendar_year: {
      message: 'Dernière année civile',
    },
    skyux_date_range_picker_format_label_this_calendar_year: {
      message: 'Cette année civile',
    },
    skyux_date_range_picker_format_label_next_calendar_year: {
      message: 'Prochaine année civile',
    },
    skyux_date_range_picker_format_label_last_fiscal_year: {
      message: 'Dernier exercice',
    },
    skyux_date_range_picker_format_label_this_fiscal_year: {
      message: 'L’exercice en cours',
    },
    skyux_date_range_picker_format_label_next_fiscal_year: {
      message: 'Le prochain exercice',
    },
    skyux_date_range_picker_start_date_label: {
      message: 'À partir de la date du',
    },
    skyux_date_range_picker_end_date_label: { message: "Jusqu'à la date du" },
    skyux_date_range_picker_before_date_label: { message: 'Date avant' },
    skyux_date_range_picker_after_date_label: { message: 'Date après' },
    skyux_date_range_picker_default_aria_label: { message: '{0} pour {1}' },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyDatetimeResourcesModule {}
