/* istanbul ignore file */
/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-lists' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    skyux_filter_aria_label_descriptor: { message: 'Filter {0}' },
    skyux_filter_button_title: { message: 'Filter' },
    skyux_filter_summary_close: { message: 'Remove filter' },
    skyux_filter_summary_header: { message: 'Filter' },
    skyux_infinite_scroll_load_more_button: { message: 'Load more' },
    skyux_paging_label: { message: 'Pagination' },
    skyux_paging_loaded: { message: 'Page {0} loaded.' },
    skyux_paging_loading: { message: 'Loading page {0}' },
    skyux_paging_next: { message: 'Next' },
    skyux_paging_page_label: { message: 'Page {0} of {1}' },
    skyux_paging_page_link_aria_label: { message: 'Page {0}' },
    skyux_paging_previous: { message: 'Previous' },
    skyux_repeater_label: { message: 'List of items' },
    skyux_repeater_item_collapse: { message: 'Collapse {0}' },
    skyux_repeater_item_collapse_default: { message: 'Collapse' },
    skyux_repeater_item_expand: { message: 'Expand {0}' },
    skyux_repeater_item_expand_default: { message: 'Expand' },
    skyux_repeater_item_checkbox_label: { message: 'Select {0}' },
    skyux_repeater_item_checkbox_label_default: { message: 'Select row' },
    skyux_repeater_item_reorder_cancel: {
      message:
        'Item reordering was canceled. The item was returned to its original position.',
    },
    skyux_repeater_item_reorder_finish: {
      message: 'Dropped the item in position',
    },
    skyux_repeater_item_reorder_instructions: {
      message:
        'Item grabbed. Press the up and down arrow keys to change position. Press the spacebar or enter key to drop. And press the escape key to cancel.',
    },
    skyux_repeater_item_reorder_moved: {
      message: 'Moved the item to position',
    },
    skyux_repeater_item_reorder_label_default: { message: 'Reorder' },
    skyux_repeater_item_reorder_label: { message: 'Reorder {0}' },
    skyux_repeater_item_reorder_operation: {
      message: 'Press the spacebar or enter key to reorder.',
    },
    skyux_repeater_item_reorder_top: { message: 'Top' },
    skyux_repeater_item_reorder_top_label: { message: 'Move {0} to top' },
    skyux_repeater_item_reorder_top_label_default: { message: 'Move to top' },
    skyux_sort_aria_label_descriptor: { message: 'Sort {0}' },
    skyux_sort_button_label: { message: 'Sort' },
    skyux_sort_menu_heading: { message: 'Sort by' },
  },
  'FR-CA': {
    skyux_filter_aria_label_descriptor: { message: 'Filtrer {0}' },
    skyux_filter_button_title: { message: 'Filtre' },
    skyux_filter_summary_close: { message: 'Retirer le filtre' },
    skyux_filter_summary_header: { message: 'Filtre' },
    skyux_infinite_scroll_load_more_button: { message: 'Charger encore' },
    skyux_paging_label: { message: 'Pagination' },
    skyux_paging_loaded: { message: 'Page {0} chargée.' },
    skyux_paging_loading: { message: 'Chargement de la page {0}' },
    skyux_paging_next: { message: 'Suivant' },
    skyux_paging_page_label: { message: 'Page {0} de {1}' },
    skyux_paging_page_link_aria_label: { message: 'Page {0}' },
    skyux_paging_previous: { message: 'Précédent' },
    skyux_repeater_label: { message: 'Liste des éléments' },
    skyux_repeater_item_collapse: { message: 'Réduire {0}' },
    skyux_repeater_item_collapse_default: { message: 'Réduire' },
    skyux_repeater_item_expand: { message: 'Agrandir {0}' },
    skyux_repeater_item_expand_default: { message: 'Agrandir' },
    skyux_repeater_item_checkbox_label: { message: 'Sélectionner {0}' },
    skyux_repeater_item_checkbox_label_default: {
      message: 'Sélectionner une ligne',
    },
    skyux_repeater_item_reorder_cancel: {
      message:
        'La réorganisation de l’élément a été annulée. L’élément a été retourné à sa position initiale.',
    },
    skyux_repeater_item_reorder_finish: {
      message: 'A déposé l’élément en position',
    },
    skyux_repeater_item_reorder_instructions: {
      message:
        'Élément saisi. Appuyez sur les flèches vers le haut et vers le bas pour modifier la position. Appuyez sur la touche Entrée ou Espace pour déposer. Et appuyez sur la touche d’échappement pour annuler.',
    },
    skyux_repeater_item_reorder_moved: {
      message: 'L’élément a été déplacé à la position',
    },
    skyux_repeater_item_reorder_label_default: { message: 'Réorganiser' },
    skyux_repeater_item_reorder_label: { message: 'Réorganiser {0}' },
    skyux_repeater_item_reorder_operation: {
      message: 'Appuyez sur la touche Espace ou Entrée pour réorganiser.',
    },
    skyux_repeater_item_reorder_top: { message: 'Haut' },
    skyux_repeater_item_reorder_top_label: {
      message: 'Déplacer {0} dans le haut',
    },
    skyux_repeater_item_reorder_top_label_default: {
      message: 'Déplacer au haut',
    },
    skyux_sort_aria_label_descriptor: { message: 'Trier {0}' },
    skyux_sort_button_label: { message: 'Trier' },
    skyux_sort_menu_heading: { message: 'Trier par' },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyListsResourcesModule {}
