// The contents of this file are automatically generated by
// https://github.com/blackbaud/skyux-builder-plugin-stache-route-metadata
export class StacheRouteMetadataService {
  public routes: any[];
}
