/* istanbul ignore file */

/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-modals' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    skyux_confirm_dialog_default_ok_text: { message: 'OK' },
    skyux_confirm_dialog_default_yes_text: { message: 'Yes' },
    skyux_confirm_dialog_default_no_text: { message: 'No' },
    skyux_confirm_dialog_default_cancel_text: { message: 'Cancel' },
    skyux_modal_close: { message: 'Close modal' },
    skyux_modal_open_help: { message: 'Open Help' },
    skyux_modal_footer_cancel_button: { message: 'Cancel' },
    skyux_modal_footer_primary_button: { message: 'Save' },
    skyux_modal_dirty_default_message: {
      message: 'Are you sure you want to discard your changes?',
    },
    skyux_modal_dirty_default_discard_changes_text: {
      message: 'Discard changes',
    },
    skyux_modal_dirty_default_keep_working_text: { message: 'Keep working' },
  },
  ES: {
    skyux_confirm_dialog_default_ok_text: { message: 'Aceptar' },
    skyux_confirm_dialog_default_yes_text: { message: 'Sí' },
    skyux_confirm_dialog_default_no_text: { message: 'No' },
    skyux_confirm_dialog_default_cancel_text: { message: 'Cancelar' },
    skyux_modal_close: { message: 'Cerrar cuadro de diálogo modal' },
    skyux_modal_open_help: { message: 'Abrir ayuda' },
    skyux_modal_footer_cancel_button: { message: 'Cancelar' },
    skyux_modal_footer_primary_button: { message: 'Guardar' },
    skyux_modal_dirty_default_message: {
      message: '¿Está seguro de que desea descartar los cambios?',
    },
    skyux_modal_dirty_default_discard_changes_text: {
      message: 'Descartar cambios',
    },
    skyux_modal_dirty_default_keep_working_text: {
      message: 'Seguir trabajando',
    },
  },
  'FR-CA': {
    skyux_confirm_dialog_default_ok_text: { message: 'OK' },
    skyux_confirm_dialog_default_yes_text: { message: 'Oui' },
    skyux_confirm_dialog_default_no_text: { message: 'Non' },
    skyux_confirm_dialog_default_cancel_text: { message: 'Annuler' },
    skyux_modal_close: { message: 'Fermer la boîte de dialogue' },
    skyux_modal_open_help: { message: 'Ouvrir l’aide' },
    skyux_modal_footer_cancel_button: { message: 'Annuler' },
    skyux_modal_footer_primary_button: { message: 'Sauvegarder' },
    skyux_modal_dirty_default_message: {
      message: 'Êtes-vous certain de vouloir abandonner ces modifications?',
    },
    skyux_modal_dirty_default_discard_changes_text: {
      message: 'Abandonner les modifications',
    },
    skyux_modal_dirty_default_keep_working_text: {
      message: 'Continuer la modification',
    },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyModalsResourcesModule {}
