import {
  SchematicTestRunner,
  UnitTestTree,
} from '@angular-devkit/schematics/testing';

import path from 'node:path';

import { createTestApp, createTestLibrary } from '../../../testing/scaffold';

jest.mock('../../../../version', () => {
  return {
    VERSION: {
      major: 'CURRENT_VERSION',
    },
  };
});

interface TestAngularJson {
  projects: Record<
    string,
    {
      architect: Record<
        string,
        { builder?: string; options?: { styles?: string[] } }
      >;
    }
  >;
}

describe('Migrations > Add compat stylesheets', () => {
  const compatStylesheetPath = 'src/app/skyuxCURRENT_VERSION-compat.css';

  const runner = new SchematicTestRunner(
    'migrations',
    path.join(__dirname, '../../../../../migrations.json'),
  );

  async function setupTest(): Promise<{
    runSchematic: () => Promise<UnitTestTree>;
    tree: UnitTestTree;
  }> {
    const tree = await createTestApp(runner, {
      projectName: 'my-app',
    });

    return {
      runSchematic: (): Promise<UnitTestTree> =>
        runner.runSchematic('add-compat-stylesheets', {}, tree),
      tree,
    };
  }

  async function validateCompatStylesheet(
    packageJson: string,
    existingWorkspaceStylesheets: string[] | undefined,
    existingCompatStylesheet?: string,
  ): Promise<void> {
    const projectTargets = ['build', 'test'];

    const { runSchematic, tree } = await setupTest();

    tree.overwrite('/package.json', packageJson);

    if (existingCompatStylesheet) {
      tree.create(compatStylesheetPath, existingCompatStylesheet);
    }

    const angularJson = tree.readJson(
      '/angular.json',
    ) as unknown as TestAngularJson;

    for (const target of projectTargets) {
      const architectTarget = angularJson.projects['my-app'].architect[target];
      architectTarget.options ??= {};
      architectTarget.options.styles = existingWorkspaceStylesheets;
    }

    tree.overwrite('/angular.json', JSON.stringify(angularJson));

    const updatedTree = await runSchematic();

    const compatStylesheetContents = updatedTree.readText(compatStylesheetPath);

    expect(compatStylesheetContents).toContain(
      '--sky-compat-btn-disabled-pointer-events: none;',
    );
    expect(compatStylesheetContents).toContain('COMPONENT: BUTTON');

    const updatedAngularJson = updatedTree.readJson(
      '/angular.json',
    ) as unknown as TestAngularJson;

    const expectedStyles = [
      ...(existingWorkspaceStylesheets || []),
      compatStylesheetPath,
    ];

    for (const target of projectTargets) {
      expect(
        updatedAngularJson.projects['my-app'].architect[target].options?.styles,
      ).toEqual(expectedStyles);
    }
  }

  afterEach(() => {
    jest.resetAllMocks();
    jest.resetModules();
  });

  it('should not add a compat stylesheet if a corresponding library is not installed', async () => {
    const { runSchematic, tree } = await setupTest();

    tree.overwrite('/package.json', JSON.stringify({}));

    const originalAngularJson = tree.readContent('angular.json');
    const updatedTree = await runSchematic();
    const newAngularJson = updatedTree.readContent('angular.json');

    expect(updatedTree.exists(compatStylesheetPath)).toBe(false);

    // Workspace config should remain untouched.
    expect(originalAngularJson).toEqual(newAngularJson);
  });

  it('should add a compat stylesheet for libraries in dependencies', async () => {
    await validateCompatStylesheet(
      JSON.stringify({
        dependencies: {
          '@skyux/theme': 'CURRENT_VERSION.0.0',
        },
      }),
      [],
    );
  });

  it('should add a compat stylesheet for libraries in devDependencies', async () => {
    await validateCompatStylesheet(
      JSON.stringify({
        devDependencies: {
          '@skyux/theme': 'CURRENT_VERSION.0.0',
        },
      }),
      [],
    );
  });

  it('should overwrite an existing compat stylesheet', async () => {
    await validateCompatStylesheet(
      JSON.stringify({
        devDependencies: {
          '@skyux/theme': 'CURRENT_VERSION.0.0',
        },
      }),
      [],
      '/* */',
    );
  });

  it('should handle missing styles array', async () => {
    await validateCompatStylesheet(
      JSON.stringify({
        devDependencies: {
          '@skyux/theme': 'CURRENT_VERSION.0.0',
        },
      }),
      undefined, // <-- empty array
      '/* */',
    );
  });

  it('should ignore build target for libraries', async () => {
    const tree = await createTestLibrary(runner, {
      projectName: 'my-lib',
    });

    tree.overwrite(
      '/package.json',
      JSON.stringify({
        dependencies: {
          '@skyux/theme': 'CURRENT_VERSION.0.0',
        },
      }),
    );

    // The showcase app generated by `createTestLibrary` uses the modern
    // `@angular/build:unit-test` builder for `test`, which has no `styles`
    // option. Configure it with the karma builder (as real SKY UX apps use)
    // so the schematic has something to add a stylesheet to.
    const angularJsonBefore = tree.readJson(
      '/angular.json',
    ) as unknown as TestAngularJson;
    angularJsonBefore.projects['my-lib-showcase'].architect['test'] = {
      builder: '@angular/build:karma',
      options: { styles: [] },
    };
    tree.overwrite('/angular.json', JSON.stringify(angularJsonBefore));

    const updatedTree = await runner.runSchematic(
      'add-compat-stylesheets',
      {},
      tree,
    );

    const libShowcaseCompatStylesheetPath =
      'projects/my-lib-showcase/src/app/skyuxCURRENT_VERSION-compat.css';

    const angularJson = updatedTree.readJson(
      '/angular.json',
    ) as unknown as TestAngularJson;

    expect(
      angularJson.projects['my-lib'].architect['build'].options?.styles,
    ).toBeUndefined();

    expect(
      angularJson.projects['my-lib'].architect['test'].options?.styles,
    ).toBeUndefined();

    expect(updatedTree.exists(libShowcaseCompatStylesheetPath)).toEqual(true);

    expect(
      angularJson.projects['my-lib-showcase'].architect['build'].options
        ?.styles,
    ).toContain(libShowcaseCompatStylesheetPath);

    expect(
      angularJson.projects['my-lib-showcase'].architect['test'].options?.styles,
    ).toContain(libShowcaseCompatStylesheetPath);
  });
});
