/* istanbul ignore file */

/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-split-view' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    skyux_split_view_resize_handle: {
      message:
        'Resize the drawer panel. Use right arrow key to expand and left arrow key to shrink.',
    },
    skyux_split_view_back_to_list: { message: 'Back to list' },
  },
  ES: {
    skyux_split_view_resize_handle: {
      message:
        'Cambiar el tamaño del panel lateral. Utilice la tecla de flecha derecha para ampliarlo y la tecla de flecha izquierda para reducirlo.',
    },
    skyux_split_view_back_to_list: { message: 'Volver a la lista' },
  },
  'FR-CA': {
    skyux_split_view_resize_handle: {
      message:
        'Redimensionnez le panneau du menu latéral. Utilisez la flèche de droite pour agrandir et la flèche de gauche pour réduire.',
    },
    skyux_split_view_back_to_list: { message: 'Retour à la liste' },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkySplitViewResourcesModule {}
