/* istanbul ignore file */

/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/shared/sky-charts' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    'skyux_charts.chart.bar.accessible_summary': {
      message:
        "Bar chart. Number of series: {0}. Number of categories: {1}. A data table is available from the chart's context menu.",
    },
    'skyux_charts.chart.controls.context_menu.accessible_name': {
      message: 'Context menu for {0}',
    },
    'skyux_charts.chart.controls.context_menu.view_data_table': {
      message: 'View data table',
    },
    'skyux_charts.chart.line.accessible_summary': {
      message:
        "Line chart. Number of series: {0}. Number of categories: {1}. A data table is available from the chart's context menu.",
    },
    'skyux_charts.data_table_modal.close_button': { message: 'Close' },
    'skyux_charts.data_table_modal.table_region_label': {
      message: 'Data table for {0}',
    },
  },
  'FR-CA': {
    'skyux_charts.chart.bar.accessible_summary': {
      message:
        'Graphique à barres. Nombre de séries : {0}. Nombre de catégories : {1}. Un tableau de données est disponible dans le menu du contexte du graphique.',
    },
    'skyux_charts.chart.controls.context_menu.accessible_name': {
      message: 'Menu du contexte pour {0}',
    },
    'skyux_charts.chart.controls.context_menu.view_data_table': {
      message: 'Visualiser la table de données',
    },
    'skyux_charts.data_table_modal.close_button': { message: 'Fermer' },
    'skyux_charts.data_table_modal.table_region_label': {
      message: 'Tableau de données pour {0}',
    },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyChartsResourcesModule {}
