/* istanbul ignore file */
/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-flyout' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    skyux_flyout_close: { message: 'Close flyout' },
    skyux_flyout_iterator_previous_button: { message: 'Previous' },
    skyux_flyout_iterator_next_button: { message: 'Next' },
    skyux_flyout_permalink_button: { message: 'View record' },
    skyux_flyout_primary_action_button: { message: 'Create list' },
    skyux_flyout_resize_handle: {
      message:
        'Resize the flyout window. Press the enter or space key to activate, then use left arrow key to expand the flyout window and right arrow key to shrink the flyout window. Press the enter, space, or tab key to deactivate.',
    },
  },
  'FR-CA': {
    skyux_flyout_close: { message: 'Fermer la fenêtre contextuelle' },
    skyux_flyout_iterator_previous_button: { message: 'Précédent' },
    skyux_flyout_iterator_next_button: { message: 'Suivant' },
    skyux_flyout_permalink_button: { message: 'Visualiser le dossier' },
    skyux_flyout_primary_action_button: { message: 'Créer une liste' },
    skyux_flyout_resize_handle: {
      message:
        'Redimensionnez la fenêtre contextuelle. Appuyez sur la touche Entrée ou Espace pour l’activer, puis utiliser la flèche de gauche pour agrandir la fenêtre contextuelle et la flèche de droite pour réduire la fenêtre contextuelle. Appuyez sur la touche Entrée, Espace ou Tabulation pour la désactiver.',
    },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyFlyoutResourcesModule {}
