/* istanbul ignore file */
/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-pages' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    sky_action_hub_related_links: { message: 'Related links' },
    sky_action_hub_recent_links: { message: 'Recently accessed' },
    sky_action_hub_settings_links: { message: 'Settings' },
    sky_action_hub_needs_attention: { message: 'Needs attention' },
    sky_action_hub_needs_attention_empty: {
      message: 'No issues currently need attention',
    },
  },
  'FR-CA': {
    sky_action_hub_related_links: { message: 'Liens connexes' },
    sky_action_hub_recent_links: { message: 'Accédés récemment' },
    sky_action_hub_settings_links: { message: 'Paramètres' },
    sky_action_hub_needs_attention: {
      message: 'Nécessite une attention particulière',
    },
    sky_action_hub_needs_attention_empty: {
      message:
        'Aucun problème ne nécessite actuellement une attention particulière',
    },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyPagesResourcesModule {}
