import { SkyFilterBarFilterValue } from '@skyux/filter-bar';

// eslint-disable @cspell/spellchecker
export const FILTER_SELECTION_VALUES: Record<
  string,
  SkyFilterBarFilterValue[]
> = {
  'community-connection': [
    { value: 'child-of-faculty', displayValue: 'Child of faculty' },
    { value: 'child-of-alum', displayValue: 'Child of alum' },
    { value: 'grandparent-is-alum', displayValue: 'Grandchild of alum' },
    { value: 'related-to-trustee', displayValue: 'Related to trustee' },
    { value: 'sibling-candidate', displayValue: 'Sibling is candidate' },
    {
      value: 'sibling-past-candidate',
      displayValue: 'Sibling is past candidate',
    },
    { value: 'sibling-student', displayValue: 'Sibling is student' },
    { value: 'sibling alum', displayValue: 'Sibling is alum' },
    {
      value: 'sibling-incoming',
      displayValue: 'Sibling is incoming student',
    },
  ],
  'current-grade': [
    { value: 'pre-k', displayValue: 'Pre-k' },
    { value: 'kindergarten', displayValue: 'Kindergarten' },
    { value: 'grade-1', displayValue: '1st grade' },
    { value: 'grade-2', displayValue: '2nd grade' },
    { value: 'grade-3', displayValue: '3rd grade' },
    { value: 'grade-4', displayValue: '4th grade' },
    { value: 'grade-5', displayValue: '5th grade' },
    { value: 'grade-6', displayValue: '6th grade' },
    { value: 'grade-7', displayValue: '7th grade' },
    { value: 'grade-8', displayValue: '8th grade' },
    { value: 'grade-9', displayValue: '9th grade' },
    { value: 'grade-10', displayValue: '10th grade' },
    { value: 'grade-11', displayValue: '11th grade' },
    { value: 'grade-12', displayValue: '12th grade' },
  ],
  'entering-grade': [
    { value: 'pre-k', displayValue: 'Pre-k' },
    { value: 'kindergarten', displayValue: 'Kindergarten' },
    { value: 'grade-1', displayValue: '1st grade' },
    { value: 'grade-2', displayValue: '2nd grade' },
    { value: 'grade-3', displayValue: '3rd grade' },
    { value: 'grade-4', displayValue: '4th grade' },
    { value: 'grade-5', displayValue: '5th grade' },
    { value: 'grade-6', displayValue: '6th grade' },
    { value: 'grade-7', displayValue: '7th grade' },
    { value: 'grade-8', displayValue: '8th grade' },
    { value: 'grade-9', displayValue: '9th grade' },
    { value: 'grade-10', displayValue: '10th grade' },
    { value: 'grade-11', displayValue: '11th grade' },
    { value: 'grade-12', displayValue: '12th grade' },
  ],
  role: [
    { value: 'candidate', displayValue: 'Candidate' },
    { value: 'incoming-student', displayValue: 'Incoming student' },
    { value: 'student', displayValue: 'Student' },
  ],
  'staff-assigned': [
    { value: '1', displayValue: 'Solomon Hurley' },
    { value: '2', displayValue: 'Kanesha Hutto' },
    { value: '3', displayValue: 'Darcel Lenz' },
    { value: '4', displayValue: 'Cheyenne Lightfoot' },
    { value: '5', displayValue: 'Jack Lovett' },
    { value: '6', displayValue: 'Wonda Lumpkin' },
    { value: '7', displayValue: 'Kristeen Lunsford' },
    { value: '8', displayValue: 'Clarice Overton' },
    { value: '9', displayValue: 'Martine Rocha' },
    { value: '10', displayValue: 'Tonja Sanderson' },
    { value: '11', displayValue: 'Molly Seymour' },
    { value: '12', displayValue: 'Ed Sipes' },
    { value: '13', displayValue: 'Cristen Sizemore' },
    { value: '14', displayValue: 'Rod Tomlinson' },
    { value: '15', displayValue: 'Eliza Vanhorn' },
    { value: '16', displayValue: 'Jessy Witherspoon' },
    { value: '17', displayValue: 'Ilene Woo' },
  ],
};
