/* istanbul ignore file */

/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-tabs' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    skyux_tab_add: { message: 'Add tab' },
    skyux_tab_close: { message: 'Close {0} tab' },
    skyux_tabs_navigator_finish: { message: 'Finish' },
    skyux_tabs_navigator_next: { message: 'Next' },
    skyux_tabs_navigator_previous: { message: 'Previous' },
    skyux_tab_open: { message: 'Open tab' },
    skyux_vertical_tabs_show_tabs_text: { message: 'Tab list' },
    skyux_wizard_sr_step_current: { message: 'Step {0} of {1}, current: {2}' },
    skyux_wizard_sr_step_completed: {
      message: 'Step {0} of {1}, completed: {2}',
    },
    skyux_wizard_sr_step_unavailable: {
      message: 'Step {0} of {1}, unavailable: {2}',
    },
  },
  'FR-CA': {
    skyux_tab_add: { message: 'Ajouter un onglet' },
    skyux_tab_close: { message: 'Fermer l’onglet {0}' },
    skyux_tabs_navigator_finish: { message: 'Terminer' },
    skyux_tabs_navigator_next: { message: 'Suivant' },
    skyux_tabs_navigator_previous: { message: 'Précédent' },
    skyux_tab_open: { message: 'Ouvrir l’onglet' },
    skyux_vertical_tabs_show_tabs_text: { message: 'Liste des onglets' },
    skyux_wizard_sr_step_current: {
      message: 'Étape {0} de {1}, en cours : {2}',
    },
    skyux_wizard_sr_step_completed: {
      message: 'Étape {0} de {1}, terminée : {2}',
    },
    skyux_wizard_sr_step_unavailable: {
      message: 'Étape {0} de {1}, non disponible : {2}',
    },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyTabsResourcesModule {}
