import { SkyAutocompleteHarness } from '../autocomplete/autocomplete-harness';

import { SkyLookupShowMorePickerHarness } from './lookup-show-more-picker-harness';

export class SkyLookupHarness extends SkyAutocompleteHarness {
  // This class name is generated by the lookup component when it is placed inside an input box component.
  public static hostSelector = '.sky-input-box__lookup';

  #documentRootLocator = this.documentRootLocatorFactory();

  public async getShowMorePicker(): Promise<SkyLookupShowMorePickerHarness> {
    const pickerId = await (
      await (await this.getInputHarness()).host()
    ).getAttribute('data-sky-lookup-show-more-picker-id');

    const defaultPicker = await this.#documentRootLocator.locatorFor(
      SkyLookupShowMorePickerHarness.with({ selector: `#${pickerId}` })
    )();

    return defaultPicker;
  }

  // TODO: Get token values
}
