/* istanbul ignore file */
/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-docs-tools' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    sky_docs_code_snippet_copy_to_clipboard_button_label: { message: 'Copy' },
    sky_docs_code_snippet_copy_to_clipboard_success_message: {
      message: 'Code copied',
    },
    sky_docs_code_example_viewer_demo_hidden_message: {
      message: 'Open this code example in StackBlitz to view the demo.',
    },
    sky_docs_code_example_viewer_demo_stack_blitz_button: {
      message: 'Edit in StackBlitz',
    },
    sky_docs_code_example_viewer_hide_code_button_label: {
      message: 'Hide code',
    },
    sky_docs_code_example_viewer_show_code_button_label: {
      message: 'Show code',
    },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyDocsToolsResourcesModule {}
