/* istanbul ignore file */
/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-help-inline' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    skyux_help_inline_button_title: { message: 'Show help content' },
    skyux_help_inline_aria_label: { message: 'Show help content for {0}' },
  },
  'FR-CA': {
    skyux_help_inline_button_title: {
      message: 'Afficher le contenu de l’aide',
    },
    skyux_help_inline_aria_label: {
      message: 'Afficher le contenu de l’aide pour {0}',
    },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyHelpInlineResourcesModule {}
