name: nx-set-shas
description: Set the shas based on changes since the last successful workflow run.
inputs:
  workflow-id:
    description: 'The ID of the workflow to track or name of the file name. E.g. ci.yml.'
    required: true
outputs:
  base:
    description: 'The base sha to use for nx affected commands.'
    value: ${{ steps.nx-set-shas.outputs.base || steps.set-shas.outputs.base }}
  base-branch:
    description: 'The base branch to use for nx affected commands.'
    value: ${{ steps.read-default-base.outputs.main-branch-name }}
  head:
    description: 'The head sha to use for nx affected commands.'
    value: ${{ steps.nx-set-shas.outputs.head || steps.set-shas.outputs.head }}
  pr-number:
    description: 'The PR number for all events, including workflow_dispatch.'
    value: ${{ steps.workflow-dispatch.outputs.pr-number || github.event.number }}
  pr-labels:
    description: 'The PR labels for all events, including workflow_dispatch.'
    value: ${{ steps.workflow-dispatch.outputs.pr-labels || toJson( github.event.pull_request.labels.*.name ) }}
runs:
  using: 'composite'
  steps:
    - name: Read default base from .skyuxdev.json
      id: read-default-base
      shell: bash
      run: |
        echo "main-branch-name=$(jq -r '.baseBranch' .skyuxdev.json)" >> $GITHUB_OUTPUT

    - name: Derive appropriate SHAs for base and head for `nx affected` commands (using nrwl/nx-set-shas).
      id: nx-set-shas
      uses: nrwl/nx-set-shas@9885af301bd1be213e975f11ae32c6daeadc4a87 # 4.3.3
      with:
        main-branch-name: ${{ steps.read-default-base.outputs.main-branch-name }}
        workflow-id: ${{ inputs.workflow-id }}

    - name: Fetch PR information (workflow_dispatch).
      if: ${{ github.event_name == 'workflow_dispatch' }}
      id: workflow-dispatch
      uses: actions/github-script@v8
      with:
        script: |
          // Find the last workflow run that intersects with commits to this PR.
          const pullRequests = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            base: '${{ steps.read-default-base.outputs.main-branch-name }}',
            head: `${context.repo.owner}:${process.env.GITHUB_REF_NAME}`
          });
          if (pullRequests.data.length > 0) {
            pullRequests.data.sort((a, b) => b.created_at.localeCompare(a.created_at));
            core.setOutput('pr-number', pullRequests.data[0].number);
            core.setOutput('pr-created_at', pullRequests.data[0].created_at);
            core.setOutput('pr-labels', JSON.stringify(pullRequests.data[0].labels.map(label => label.name)));
          } else {
            core.setFailed(`Unable to find an open PR for branch ${process.env.GITHUB_REF_NAME}`);
            process.exit(1);
          }

    - name: Log base and head SHAs used for nx affected
      shell: bash
      run: |
        echo "Base SHA"
        echo ${{ steps.nx-set-shas.outputs.base }}
        echo ""
        echo "Head SHA"
        echo ${{ steps.nx-set-shas.outputs.head }}
        echo ""
