name: E2E Affected Check
description: 'Check if e2e tests are affected by the changes since the last visual snapshot'
inputs:
  project:
    description: 'The name of the project'
    required: true
  base:
    description: 'The base commit to compare against'
    required: true
  head:
    description: 'The head commit to compare with'
    required: true
  percy-token:
    description: 'The Percy API token'
    required: true
outputs:
  affected:
    description: 'Whether the e2e tests are affected by the changes'
    value: ${{ steps.affected.outputs.affected }}
runs:
  using: 'composite'
  steps:
    - name: Build e2e-schematics
      shell: bash
      run: npx nx build e2e-schematics
    - name: Check if e2e tests are affected by the changes
      id: affected
      uses: actions/github-script@v6
      with:
        script: |
          const options = {
            method: 'GET',
            headers: {
              Authorization: 'Token ${{ inputs.percy-token }}'
            }
          };

          const shas = await exec.getExecOutput('git', ['log', '--format=%H', '${{ inputs.base }}..${{ inputs.head }}'])
            .then(({stdout}) => stdout.trim().split('\n'));

          const { getLastGoodPercyBuild } = require('./dist/libs/sdk/e2e-schematics/src/workflow');
          const lastGoodCommit = await getLastGoodPercyBuild('skyux-${{ inputs.project }}', shas, options);

          if (!lastGoodCommit) {
            core.info('No good Percy test found, running e2e tests');
            core.setOutput('affected', 'true');
            process.exit(0);
          }

          const affectedProjects = await exec.getExecOutput('npx', [
            'nx',
            'show',
            'projects',
            `--base=${lastGoodCommit}`,
            '--head=${{ inputs.head }}',
            '--withTarget=e2e',
            '--affected',
            '--json'
          ]).then(({stdout}) => JSON.parse(stdout));
          const projectAffected = affectedProjects.includes('${{ inputs.project }}');
          if (projectAffected) {
            core.info(`E2E tests affected`);
            core.setOutput('affected', 'true');
          } else {
            core.info(`No e2e tests affected since ${lastGoodCommit.substring(0, 7)}`);
            core.setOutput('affected', 'false');
          }
