/* istanbul ignore file */

/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-toast' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    skyux_toast_close_button_aria_label: { message: 'Close message:' },
    skyux_toast_close_button_title: { message: 'Close the message' },
  },
  'FR-CA': {
    skyux_toast_close_button_aria_label: { message: 'Message de fermeture :' },
    skyux_toast_close_button_title: { message: 'Fermer le message' },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyToastResourcesModule {}
