/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module modules/shared/sky-layout' schematic.
 * To update this file, simply rerun the command.
 */

import { NgModule } from '@angular/core';
import {
  getLibStringForLocale,
  SkyAppLocaleInfo,
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesProvider,
  SKY_LIB_RESOURCES_PROVIDERS
} from '@skyux/i18n';

const RESOURCES: { [locale: string]: SkyLibResources } = {
  'EN-US': {"skyux_back_to_top":{"message":"Back to top"},"skyux_card_checkbox_label":{"message":"Select card"},"skyux_definition_list_none_found":{"message":"None found"},"skyux_description_list_none_found":{"message":"None found"},"skyux_inline_delete_assistive_text":{"message":"Are you sure you want to delete this item?"},"skyux_inline_delete_cancel":{"message":"Cancel"},"skyux_inline_delete_confirm_deletion":{"message":"Confirm deletion"},"skyux_inline_delete_delete":{"message":"Delete"},"skyux_text_expand_close_text":{"message":"Close"},"skyux_text_expand_modal_title":{"message":"Expanded view"},"skyux_text_expand_see_less":{"message":"See less"},"skyux_text_expand_see_more":{"message":"See more"}},
};

export class SkyLayoutResourcesProvider implements SkyLibResourcesProvider {
  public getString(localeInfo: SkyAppLocaleInfo, name: string): string {
    return getLibStringForLocale(RESOURCES, localeInfo.locale, name);
  }
}

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
  providers: [{
    provide: SKY_LIB_RESOURCES_PROVIDERS,
    useClass: SkyLayoutResourcesProvider,
    multi: true
  }]
})
export class SkyLayoutResourcesModule { }
