/* istanbul ignore file */
/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-popovers' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    skyux_dropdown_context_menu_default_label: { message: 'Context menu' },
    skyux_dropdown_context_menu_with_content_descriptor_default_label: {
      message: 'Context menu for {0}',
    },
    skyux_dropdown_context_menu_with_content_descriptor_el_default_label: {
      message: 'Context menu for ',
    },
  },
  'FR-CA': {
    skyux_dropdown_context_menu_default_label: { message: 'Menu du contexte' },
    skyux_dropdown_context_menu_with_content_descriptor_default_label: {
      message: 'Menu du contexte pour {0}',
    },
    skyux_dropdown_context_menu_with_content_descriptor_el_default_label: {
      message: 'Menu du contexte pour ',
    },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyPopoversResourcesModule {}
