name: CI - Affected

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.8
    with:
      number-of-agents: 3
      init-commands: |
        npx nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
        npx ngcc
      parallel-commands: |
        npx nx-cloud record -- npx nx workspace-lint
        npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        npx ngcc && npx nx affected --target=lint --quiet --silent --parallel
        npx ngcc && npx nx affected --target=test --browsers=ChromeHeadless --code-coverage --parallel --progress=false --source-map --watch=false
        npx ngcc && npx nx affected --target=posttest --browsers=ChromeHeadless --parallel --watch=false --code-coverage
        npx ngcc && npx nx affected --target=build --parallel

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.8
    with:
      number-of-agents: 3
