name: E2E Check

on:
  push:
  status:
  workflow_dispatch:

jobs:
  e2e-check-rerun:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || ( github.event.state == 'success' && startsWith( github.event.context, 'percy/' ) ) }}
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const sha = (context.commit && context.commit.sha) || context.after;
            console.log(`Finding e2e workflow run for commit ${sha}.`);
            const { data } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'e2e.yml',
              head_sha: sha,
              status: 'completed',
              per_page: 1
            });

            if (data['total_count'] === 0) {
              console.log('No e2e workflow run found.');
              process.exit(0);
            }

            const run = data.workflow_runs[0];
            if (run['conclusion'] === 'failure') {

              console.log(`Getting jobs for e2e workflow run ${run.id}.`);
              const {data} = await github.rest.actions.listJobsForWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run.id,
                per_page: 100,
                filter: 'latest'
              });
              const e2eReviewJob = (data.jobs || []).find(job => job.name === 'E2E Visual Review');

              if (
                e2eReviewJob &&
                e2eReviewJob['status'] === 'completed' &&
                e2eReviewJob['conclusion'] === 'failure'
              ) {

                console.log(`Re-running E2E Visual Review job ${e2eReviewJob.id} for workflow run ${run.id}.`);
                await github.rest.actions.reRunJobForWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  job_id: e2eReviewJob.id
                });

              } else if (e2eReviewJob) {

                console.log(`E2E Visual Review job ${e2eReviewJob.id} for workflow run ${run.id} is ${e2eReviewJob.status}.`);

              } else {

                console.log(`No E2E Visual Review job found for workflow run ${run.id}.`);

              }

            } else if (run['conclusion'] === 'success') {

              console.log(`E2E workflow run ${run.id} succeeded.`);

            } else {

              console.log(`E2E workflow run ${run.id} is ${run.status}.`);

            }
