name: Publish

on:
  push:
    tags:
      - '*.*.*'

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Build and publish
        run: |
          export NX_CLOUD_DISTRIBUTED_EXECUTION=false
          npm run ci:create-packages-dist
          npm run ci:publish-packages-dist
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: Successfully published SKY UX ${{ steps.vars.outputs.tag }} to NPM. http://github.com/${{ github.repository }}/blob/main/CHANGELOG.md
          SLACK_ICON: https://github.com/blackbaud.png?size=48
          SLACK_USERNAME: SKY UX
