on:
  workflow_dispatch:
    inputs:
      pr:
        description: 'Pull request number'
        required: true
        type: number
jobs:
  update-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.updateBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ inputs.pr }}
            });
