/* istanbul ignore file */

/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-progress-indicator' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    skyux_progress_indicator_navigator_finish: { message: 'Finish' },
    skyux_progress_indicator_navigator_next: { message: 'Next' },
    skyux_progress_indicator_navigator_previous: { message: 'Previous' },
    skyux_progress_indicator_navigator_reset: { message: 'Reset' },
  },
  'FR-CA': {
    skyux_progress_indicator_navigator_finish: { message: 'Terminer' },
    skyux_progress_indicator_navigator_next: { message: 'Suivant' },
    skyux_progress_indicator_navigator_previous: { message: 'Précédent' },
    skyux_progress_indicator_navigator_reset: { message: 'Réinitialiser' },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyProgressIndicatorResourcesModule {}
