/**
 * Course catalog sample data for data-grid demos.
 *
 * NOTE: This dataset is synthetic (no real people/instructor data).
 */

export type CourseCatalogRow = {
  id: string;
  year: number;
  term: 'Fall' | 'Spring' | 'Summer';
  yearTerm: string;
  subject: string;
  courseNumber: number;
  courseId: string;
  section: string;
  title: string;
  description: string;
  creditHours: string;
  format: 'Lecture' | 'Seminar' | 'Lab' | 'Studio' | 'Online' | 'Hybrid';
  meetingDays: 'MWF' | 'TR' | 'M' | 'W' | 'R';
  startTime: string; // HH:mm
  endTime: string; // HH:mm
  location: string;
  instructor: string;
  capacity: number;
  enrolled: number;
  status: 'Open' | 'Closed' | 'Waitlist';
  degreeAttributes: string;
};

export const data: Omit<CourseCatalogRow, 'id'>[] = [
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'CS',
    courseNumber: 330,
    courseId: 'CS330',
    section: '02',
    title: 'Software Design',
    description:
      'Software Design. Focuses on methods, tools, and ethical practice.',
    creditHours: '1',
    format: 'Hybrid',
    meetingDays: 'MWF',
    startTime: '10:30',
    endTime: '11:20',
    location: 'Morrill Hall 211',
    instructor: 'Morgan Martinez',
    capacity: 120,
    enrolled: 3,
    status: 'Open',
    degreeAttributes: 'Quantitative Reasoning; Communication',
  },
  {
    year: 2025,
    term: 'Fall',
    yearTerm: '2025-fa',
    subject: 'ART',
    courseNumber: 450,
    courseId: 'ART450',
    section: '03',
    title: 'Advanced Drawing',
    description:
      'Advanced Drawing. Covers foundational theory and practical techniques.',
    creditHours: '1',
    format: 'Lab',
    meetingDays: 'M',
    startTime: '10:30',
    endTime: '11:20',
    location: 'Goldwin Smith 409',
    instructor: 'Casey Lewis',
    capacity: 20,
    enrolled: 14,
    status: 'Open',
    degreeAttributes: 'Social Science; Writing Intensive',
  },
  {
    year: 2026,
    term: 'Summer',
    yearTerm: '2026-su',
    subject: 'PSYC',
    courseNumber: 530,
    courseId: 'PSYC530',
    section: '01',
    title: 'Cognitive Psychology',
    description:
      'Cognitive Psychology. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '2',
    format: 'Lecture',
    meetingDays: 'W',
    startTime: '10:30',
    endTime: '11:45',
    location: 'Goldwin Smith 183',
    instructor: 'Riley Johnson',
    capacity: 35,
    enrolled: 17,
    status: 'Open',
    degreeAttributes: 'Quantitative Reasoning',
  },
  {
    year: 2025,
    term: 'Spring',
    yearTerm: '2025-sp',
    subject: 'ENGL',
    courseNumber: 530,
    courseId: 'ENGL530',
    section: '03',
    title: 'Graduate Advanced Creative Writing',
    description:
      'Graduate Advanced Creative Writing. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '4',
    format: 'Lab',
    meetingDays: 'R',
    startTime: '13:00',
    endTime: '13:50',
    location: 'Goldwin Smith 208',
    instructor: 'Parker Lee',
    capacity: 60,
    enrolled: 56,
    status: 'Closed',
    degreeAttributes: 'Writing Intensive',
  },
  {
    year: 2024,
    term: 'Summer',
    yearTerm: '2024-su',
    subject: 'EDUC',
    courseNumber: 540,
    courseId: 'EDUC540',
    section: '04',
    title: 'Graduate Educational Technology',
    description:
      'Graduate Educational Technology. Includes case studies and small-group activities.',
    creditHours: '1-3',
    format: 'Seminar',
    meetingDays: 'MWF',
    startTime: '16:00',
    endTime: '16:50',
    location: 'Olin Library 421',
    instructor: 'Taylor Lewis',
    capacity: 60,
    enrolled: 38,
    status: 'Open',
    degreeAttributes: 'Ethics; Writing Intensive',
  },
  {
    year: 2026,
    term: 'Spring',
    yearTerm: '2026-sp',
    subject: 'EDUC',
    courseNumber: 110,
    courseId: 'EDUC110',
    section: '03',
    title: 'Educational Technology',
    description:
      'Educational Technology. Students complete a final project demonstrating key skills.',
    creditHours: '1',
    format: 'Lab',
    meetingDays: 'W',
    startTime: '13:30',
    endTime: '14:20',
    location: 'Baker Hall 469',
    instructor: 'Drew Smith',
    capacity: 100,
    enrolled: 97,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2026,
    term: 'Spring',
    yearTerm: '2026-sp',
    subject: 'GEOG',
    courseNumber: 530,
    courseId: 'GEOG530',
    section: '02',
    title: 'GIS Fundamentals',
    description:
      'GIS Fundamentals. Focuses on methods, tools, and ethical practice.',
    creditHours: '1',
    format: 'Online',
    meetingDays: 'MWF',
    startTime: '14:30',
    endTime: '15:20',
    location: 'Goldwin Smith 257',
    instructor: 'Morgan Nguyen',
    capacity: 35,
    enrolled: 5,
    status: 'Open',
    degreeAttributes: 'Social Science; Ethics',
  },
  {
    year: 2024,
    term: 'Fall',
    yearTerm: '2024-fa',
    subject: 'PHIL',
    courseNumber: 520,
    courseId: 'PHIL520',
    section: '03',
    title: 'Philosophy of Mind',
    description:
      'Philosophy of Mind. Focuses on methods, tools, and ethical practice.',
    creditHours: '1-3',
    format: 'Seminar',
    meetingDays: 'M',
    startTime: '12:30',
    endTime: '13:45',
    location: 'Phillips Hall 364',
    instructor: 'Cameron Patel',
    capacity: 35,
    enrolled: 14,
    status: 'Open',
    degreeAttributes: 'Humanities',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'INFO',
    courseNumber: 200,
    courseId: 'INFO200',
    section: '01',
    title: 'Information Policy',
    description:
      'Information Policy. Includes case studies and small-group activities.',
    creditHours: '1',
    format: 'Hybrid',
    meetingDays: 'M',
    startTime: '12:00',
    endTime: '12:50',
    location: 'Morrill Hall 363',
    instructor: 'Morgan Smith',
    capacity: 75,
    enrolled: 27,
    status: 'Open',
    degreeAttributes: 'Quantitative Reasoning; Ethics',
  },
  {
    year: 2025,
    term: 'Fall',
    yearTerm: '2025-fa',
    subject: 'CHEM',
    courseNumber: 160,
    courseId: 'CHEM160',
    section: '03',
    title: 'Physical Chemistry',
    description:
      'Physical Chemistry. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '4',
    format: 'Studio',
    meetingDays: 'W',
    startTime: '09:00',
    endTime: '09:50',
    location: 'Goldwin Smith 155',
    instructor: 'Morgan Kim',
    capacity: 35,
    enrolled: 34,
    status: 'Closed',
    degreeAttributes: 'Ethics',
  },
  {
    year: 2025,
    term: 'Spring',
    yearTerm: '2025-sp',
    subject: 'PHYS',
    courseNumber: 170,
    courseId: 'PHYS170',
    section: '01',
    title: 'Mechanics',
    description: 'Mechanics. Introduces core concepts with hands-on exercises.',
    creditHours: '1-3',
    format: 'Hybrid',
    meetingDays: 'TR',
    startTime: '09:00',
    endTime: '09:50',
    location: 'Statler Hall 348',
    instructor: 'Cameron Kim',
    capacity: 60,
    enrolled: 57,
    status: 'Open',
    degreeAttributes: 'Ethics',
  },
  {
    year: 2025,
    term: 'Spring',
    yearTerm: '2025-sp',
    subject: 'LING',
    courseNumber: 360,
    courseId: 'LING360',
    section: '04',
    title: 'Phonetics',
    description: 'Phonetics. Focuses on methods, tools, and ethical practice.',
    creditHours: '3',
    format: 'Seminar',
    meetingDays: 'R',
    startTime: '12:00',
    endTime: '13:50',
    location: 'Baker Hall 482',
    instructor: 'Riley Nguyen',
    capacity: 20,
    enrolled: 18,
    status: 'Closed',
    degreeAttributes: 'Humanities',
  },
  {
    year: 2024,
    term: 'Fall',
    yearTerm: '2024-fa',
    subject: 'BIOL',
    courseNumber: 510,
    courseId: 'BIOL510',
    section: '02',
    title: 'Advanced Evolution',
    description:
      'Advanced Evolution. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '1-3',
    format: 'Seminar',
    meetingDays: 'R',
    startTime: '09:00',
    endTime: '10:15',
    location: 'Hollister Hall 367',
    instructor: 'Riley Smith',
    capacity: 35,
    enrolled: 20,
    status: 'Open',
    degreeAttributes: 'Ethics',
  },
  {
    year: 2026,
    term: 'Summer',
    yearTerm: '2026-su',
    subject: 'ANTH',
    courseNumber: 450,
    courseId: 'ANTH450',
    section: '01',
    title: 'Cultural Anthropology',
    description:
      'Cultural Anthropology. Students complete a final project demonstrating key skills.',
    creditHours: '1',
    format: 'Online',
    meetingDays: 'M',
    startTime: '10:00',
    endTime: '11:50',
    location: 'Olin Library 278',
    instructor: 'Jordan Kim',
    capacity: 45,
    enrolled: 18,
    status: 'Open',
    degreeAttributes: 'Writing Intensive; Communication',
  },
  {
    year: 2026,
    term: 'Summer',
    yearTerm: '2026-su',
    subject: 'CS',
    courseNumber: 540,
    courseId: 'CS540',
    section: '01',
    title: 'Advanced Software Design',
    description:
      'Advanced Software Design. Introduces core concepts with hands-on exercises.',
    creditHours: '1-3',
    format: 'Hybrid',
    meetingDays: 'R',
    startTime: '11:30',
    endTime: '12:45',
    location: 'Sage Hall 467',
    instructor: 'Riley Kim',
    capacity: 40,
    enrolled: 32,
    status: 'Closed',
    degreeAttributes: 'Humanities',
  },
  {
    year: 2026,
    term: 'Spring',
    yearTerm: '2026-sp',
    subject: 'ENGL',
    courseNumber: 100,
    courseId: 'ENGL100',
    section: '03',
    title: 'Literary Analysis',
    description:
      'Literary Analysis. Includes case studies and small-group activities.',
    creditHours: '3',
    format: 'Hybrid',
    meetingDays: 'W',
    startTime: '11:30',
    endTime: '13:20',
    location: 'Tjaden Hall 104',
    instructor: 'Jordan Patel',
    capacity: 30,
    enrolled: 17,
    status: 'Open',
    degreeAttributes: 'Natural Science',
  },
  {
    year: 2024,
    term: 'Fall',
    yearTerm: '2024-fa',
    subject: 'ANTH',
    courseNumber: 300,
    courseId: 'ANTH300',
    section: '03',
    title: 'Cultural Anthropology',
    description:
      'Cultural Anthropology. Explores historical context and contemporary applications.',
    creditHours: '2',
    format: 'Hybrid',
    meetingDays: 'W',
    startTime: '10:30',
    endTime: '12:20',
    location: 'Hollister Hall 483',
    instructor: 'Taylor Kim',
    capacity: 30,
    enrolled: 25,
    status: 'Open',
    degreeAttributes: 'Humanities; Social Science',
  },
  {
    year: 2025,
    term: 'Spring',
    yearTerm: '2025-sp',
    subject: 'PHYS',
    courseNumber: 320,
    courseId: 'PHYS320',
    section: '01',
    title: 'Astrophysics',
    description:
      'Astrophysics. Students complete a final project demonstrating key skills.',
    creditHours: '4',
    format: 'Lecture',
    meetingDays: 'M',
    startTime: '12:00',
    endTime: '13:15',
    location: 'Uris Hall 216',
    instructor: 'Morgan Nguyen',
    capacity: 35,
    enrolled: 25,
    status: 'Open',
    degreeAttributes: 'Social Science',
  },
  {
    year: 2025,
    term: 'Spring',
    yearTerm: '2025-sp',
    subject: 'GEOG',
    courseNumber: 480,
    courseId: 'GEOG480',
    section: '03',
    title: 'Advanced Human Geography',
    description:
      'Advanced Human Geography. Introduces core concepts with hands-on exercises.',
    creditHours: '2',
    format: 'Lab',
    meetingDays: 'R',
    startTime: '13:00',
    endTime: '13:50',
    location: 'Statler Hall 276',
    instructor: 'Drew Lewis',
    capacity: 45,
    enrolled: 27,
    status: 'Open',
    degreeAttributes: 'Quantitative Reasoning; Natural Science',
  },
  {
    year: 2026,
    term: 'Spring',
    yearTerm: '2026-sp',
    subject: 'CS',
    courseNumber: 580,
    courseId: 'CS580',
    section: '02',
    title: 'Web Development',
    description:
      'Web Development. Includes case studies and small-group activities.',
    creditHours: '1-3',
    format: 'Lab',
    meetingDays: 'M',
    startTime: '14:00',
    endTime: '15:50',
    location: 'Tjaden Hall 258',
    instructor: 'Parker Brown',
    capacity: 45,
    enrolled: 25,
    status: 'Open',
    degreeAttributes: 'Quantitative Reasoning',
  },
  {
    year: 2026,
    term: 'Spring',
    yearTerm: '2026-sp',
    subject: 'ART',
    courseNumber: 590,
    courseId: 'ART590',
    section: '03',
    title: 'Graduate Photography',
    description:
      'Graduate Photography. Introduces core concepts with hands-on exercises.',
    creditHours: '2',
    format: 'Lab',
    meetingDays: 'W',
    startTime: '15:30',
    endTime: '16:45',
    location: 'Phillips Hall 445',
    instructor: 'Morgan Martinez',
    capacity: 75,
    enrolled: 21,
    status: 'Open',
    degreeAttributes: 'Diversity & Inclusion',
  },
  {
    year: 2024,
    term: 'Summer',
    yearTerm: '2024-su',
    subject: 'ANTH',
    courseNumber: 230,
    courseId: 'ANTH230',
    section: '02',
    title: 'Cultural Anthropology',
    description:
      'Cultural Anthropology. Explores historical context and contemporary applications.',
    creditHours: '2',
    format: 'Lecture',
    meetingDays: 'W',
    startTime: '16:00',
    endTime: '17:15',
    location: 'Hollister Hall 199',
    instructor: 'Drew Clark',
    capacity: 60,
    enrolled: 31,
    status: 'Closed',
    degreeAttributes: 'Natural Science',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'CHEM',
    courseNumber: 430,
    courseId: 'CHEM430',
    section: '02',
    title: 'Advanced Physical Chemistry',
    description:
      'Advanced Physical Chemistry. Students complete a final project demonstrating key skills.',
    creditHours: '1',
    format: 'Seminar',
    meetingDays: 'R',
    startTime: '16:00',
    endTime: '17:15',
    location: 'Tjaden Hall 404',
    instructor: 'Riley Lewis',
    capacity: 75,
    enrolled: 64,
    status: 'Closed',
    degreeAttributes: 'Natural Science; Diversity & Inclusion',
  },
  {
    year: 2025,
    term: 'Spring',
    yearTerm: '2025-sp',
    subject: 'ENGL',
    courseNumber: 240,
    courseId: 'ENGL240',
    section: '04',
    title: 'Literary Analysis',
    description:
      'Literary Analysis. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '4',
    format: 'Lab',
    meetingDays: 'M',
    startTime: '10:30',
    endTime: '11:20',
    location: 'Goldwin Smith 263',
    instructor: 'Jamie Patel',
    capacity: 30,
    enrolled: 4,
    status: 'Open',
    degreeAttributes: 'Natural Science; Diversity & Inclusion',
  },
  {
    year: 2024,
    term: 'Spring',
    yearTerm: '2024-sp',
    subject: 'STAT',
    courseNumber: 380,
    courseId: 'STAT380',
    section: '04',
    title: 'Statistical Computing',
    description:
      'Statistical Computing. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '2',
    format: 'Lecture',
    meetingDays: 'MWF',
    startTime: '15:30',
    endTime: '17:20',
    location: 'Hollister Hall 294',
    instructor: 'Cameron Nguyen',
    capacity: 45,
    enrolled: 19,
    status: 'Closed',
    degreeAttributes: 'Quantitative Reasoning; Communication',
  },
  {
    year: 2025,
    term: 'Spring',
    yearTerm: '2025-sp',
    subject: 'PHIL',
    courseNumber: 160,
    courseId: 'PHIL160',
    section: '03',
    title: 'Philosophy of Mind',
    description:
      'Philosophy of Mind. Explores historical context and contemporary applications.',
    creditHours: '4',
    format: 'Hybrid',
    meetingDays: 'R',
    startTime: '11:30',
    endTime: '12:20',
    location: 'Tjaden Hall 113',
    instructor: 'Quinn Wilson',
    capacity: 120,
    enrolled: 84,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2025,
    term: 'Fall',
    yearTerm: '2025-fa',
    subject: 'LING',
    courseNumber: 200,
    courseId: 'LING200',
    section: '03',
    title: 'Syntax',
    description:
      'Syntax. Explores historical context and contemporary applications.',
    creditHours: '2',
    format: 'Lab',
    meetingDays: 'W',
    startTime: '16:30',
    endTime: '17:45',
    location: 'Uris Hall 485',
    instructor: 'Hayden Brown',
    capacity: 40,
    enrolled: 5,
    status: 'Closed',
    degreeAttributes: '',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'PSYC',
    courseNumber: 210,
    courseId: 'PSYC210',
    section: '01',
    title: 'Cognitive Psychology',
    description:
      'Cognitive Psychology. Focuses on methods, tools, and ethical practice.',
    creditHours: '2',
    format: 'Seminar',
    meetingDays: 'TR',
    startTime: '09:00',
    endTime: '09:50',
    location: 'Phillips Hall 442',
    instructor: 'Jordan Wilson',
    capacity: 35,
    enrolled: 29,
    status: 'Open',
    degreeAttributes: 'Natural Science',
  },
  {
    year: 2026,
    term: 'Summer',
    yearTerm: '2026-su',
    subject: 'CHEM',
    courseNumber: 240,
    courseId: 'CHEM240',
    section: '01',
    title: 'Organic Chemistry',
    description:
      'Organic Chemistry. Students complete a final project demonstrating key skills.',
    creditHours: '1-3',
    format: 'Lab',
    meetingDays: 'TR',
    startTime: '15:30',
    endTime: '17:20',
    location: 'Morrill Hall 403',
    instructor: 'Drew Walker',
    capacity: 35,
    enrolled: 6,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'PSYC',
    courseNumber: 560,
    courseId: 'PSYC560',
    section: '03',
    title: 'Cognitive Psychology',
    description:
      'Cognitive Psychology. Students complete a final project demonstrating key skills.',
    creditHours: '4',
    format: 'Studio',
    meetingDays: 'W',
    startTime: '10:30',
    endTime: '11:45',
    location: 'Olin Library 322',
    instructor: 'Taylor Clark',
    capacity: 100,
    enrolled: 83,
    status: 'Open',
    degreeAttributes: 'Communication; Quantitative Reasoning',
  },
  {
    year: 2026,
    term: 'Summer',
    yearTerm: '2026-su',
    subject: 'ENGL',
    courseNumber: 330,
    courseId: 'ENGL330',
    section: '01',
    title: 'World Literature',
    description:
      'World Literature. Focuses on methods, tools, and ethical practice.',
    creditHours: '2',
    format: 'Studio',
    meetingDays: 'MWF',
    startTime: '16:30',
    endTime: '17:45',
    location: 'Phillips Hall 266',
    instructor: 'Taylor Lee',
    capacity: 35,
    enrolled: 22,
    status: 'Open',
    degreeAttributes: 'Writing Intensive',
  },
  {
    year: 2026,
    term: 'Spring',
    yearTerm: '2026-sp',
    subject: 'EDUC',
    courseNumber: 180,
    courseId: 'EDUC180',
    section: '02',
    title: 'Learning Sciences',
    description:
      'Learning Sciences. Includes case studies and small-group activities.',
    creditHours: '3-4',
    format: 'Seminar',
    meetingDays: 'TR',
    startTime: '15:30',
    endTime: '17:20',
    location: 'Phillips Hall 430',
    instructor: 'Drew Lee',
    capacity: 75,
    enrolled: 2,
    status: 'Open',
    degreeAttributes: 'Quantitative Reasoning',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'ANTH',
    courseNumber: 550,
    courseId: 'ANTH550',
    section: '04',
    title: 'Human Origins',
    description:
      'Human Origins. Explores historical context and contemporary applications.',
    creditHours: '1-3',
    format: 'Hybrid',
    meetingDays: 'W',
    startTime: '14:30',
    endTime: '16:20',
    location: 'Uris Hall 256',
    instructor: 'Casey Kim',
    capacity: 25,
    enrolled: 23,
    status: 'Open',
    degreeAttributes: 'Social Science',
  },
  {
    year: 2026,
    term: 'Summer',
    yearTerm: '2026-su',
    subject: 'ART',
    courseNumber: 230,
    courseId: 'ART230',
    section: '04',
    title: 'Digital Media',
    description:
      'Digital Media. Introduces core concepts with hands-on exercises.',
    creditHours: '1-3',
    format: 'Hybrid',
    meetingDays: 'M',
    startTime: '13:00',
    endTime: '13:50',
    location: 'Sage Hall 284',
    instructor: 'Taylor Smith',
    capacity: 20,
    enrolled: 17,
    status: 'Open',
    degreeAttributes: 'Humanities',
  },
  {
    year: 2026,
    term: 'Spring',
    yearTerm: '2026-sp',
    subject: 'MATH',
    courseNumber: 410,
    courseId: 'MATH410',
    section: '01',
    title: 'Advanced Differential Equations',
    description:
      'Advanced Differential Equations. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '4',
    format: 'Studio',
    meetingDays: 'M',
    startTime: '14:00',
    endTime: '14:50',
    location: 'Phillips Hall 158',
    instructor: 'Hayden Patel',
    capacity: 60,
    enrolled: 31,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2024,
    term: 'Summer',
    yearTerm: '2024-su',
    subject: 'ANTH',
    courseNumber: 130,
    courseId: 'ANTH130',
    section: '01',
    title: 'Human Origins',
    description:
      'Human Origins. Students complete a final project demonstrating key skills.',
    creditHours: '1-3',
    format: 'Studio',
    meetingDays: 'W',
    startTime: '12:30',
    endTime: '13:45',
    location: 'Uris Hall 401',
    instructor: 'Quinn Smith',
    capacity: 120,
    enrolled: 79,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2024,
    term: 'Summer',
    yearTerm: '2024-su',
    subject: 'MUS',
    courseNumber: 310,
    courseId: 'MUS310',
    section: '02',
    title: 'Composition',
    description:
      'Composition. Explores historical context and contemporary applications.',
    creditHours: '1-3',
    format: 'Seminar',
    meetingDays: 'W',
    startTime: '10:00',
    endTime: '10:50',
    location: 'Phillips Hall 452',
    instructor: 'Skyler Lee',
    capacity: 40,
    enrolled: 2,
    status: 'Open',
    degreeAttributes: 'Writing Intensive',
  },
  {
    year: 2025,
    term: 'Fall',
    yearTerm: '2025-fa',
    subject: 'PHYS',
    courseNumber: 390,
    courseId: 'PHYS390',
    section: '02',
    title: 'Astrophysics',
    description:
      'Astrophysics. Explores historical context and contemporary applications.',
    creditHours: '1-3',
    format: 'Lecture',
    meetingDays: 'TR',
    startTime: '12:00',
    endTime: '13:15',
    location: 'Morrill Hall 130',
    instructor: 'Taylor Lewis',
    capacity: 40,
    enrolled: 38,
    status: 'Open',
    degreeAttributes: 'Social Science; Quantitative Reasoning',
  },
  {
    year: 2025,
    term: 'Summer',
    yearTerm: '2025-su',
    subject: 'ARCH',
    courseNumber: 380,
    courseId: 'ARCH380',
    section: '04',
    title: 'Urban Planning',
    description:
      'Urban Planning. Students complete a final project demonstrating key skills.',
    creditHours: '1-3',
    format: 'Lecture',
    meetingDays: 'M',
    startTime: '09:30',
    endTime: '11:20',
    location: 'Hollister Hall 228',
    instructor: 'Avery Patel',
    capacity: 35,
    enrolled: 1,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2024,
    term: 'Spring',
    yearTerm: '2024-sp',
    subject: 'GEOG',
    courseNumber: 440,
    courseId: 'GEOG440',
    section: '02',
    title: 'Environmental Geography',
    description:
      'Environmental Geography. Includes case studies and small-group activities.',
    creditHours: '1',
    format: 'Studio',
    meetingDays: 'M',
    startTime: '16:30',
    endTime: '17:45',
    location: 'Goldwin Smith 443',
    instructor: 'Jordan Walker',
    capacity: 30,
    enrolled: 10,
    status: 'Closed',
    degreeAttributes: 'Writing Intensive; Diversity & Inclusion',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'LING',
    courseNumber: 150,
    courseId: 'LING150',
    section: '03',
    title: 'Syntax',
    description: 'Syntax. Focuses on methods, tools, and ethical practice.',
    creditHours: '4',
    format: 'Lecture',
    meetingDays: 'MWF',
    startTime: '09:30',
    endTime: '10:45',
    location: 'Sage Hall 365',
    instructor: 'Riley Wilson',
    capacity: 75,
    enrolled: 56,
    status: 'Open',
    degreeAttributes: 'Writing Intensive',
  },
  {
    year: 2024,
    term: 'Spring',
    yearTerm: '2024-sp',
    subject: 'LING',
    courseNumber: 410,
    courseId: 'LING410',
    section: '01',
    title: 'Sociolinguistics',
    description:
      'Sociolinguistics. Explores historical context and contemporary applications.',
    creditHours: '3-4',
    format: 'Seminar',
    meetingDays: 'MWF',
    startTime: '11:30',
    endTime: '13:20',
    location: 'Tjaden Hall 308',
    instructor: 'Jordan Kim',
    capacity: 25,
    enrolled: 14,
    status: 'Open',
    degreeAttributes: 'Communication',
  },
  {
    year: 2025,
    term: 'Summer',
    yearTerm: '2025-su',
    subject: 'ENGL',
    courseNumber: 470,
    courseId: 'ENGL470',
    section: '04',
    title: 'Literary Analysis',
    description:
      'Literary Analysis. Students complete a final project demonstrating key skills.',
    creditHours: '4',
    format: 'Seminar',
    meetingDays: 'M',
    startTime: '12:00',
    endTime: '12:50',
    location: 'Statler Hall 274',
    instructor: 'Rowan Martinez',
    capacity: 40,
    enrolled: 0,
    status: 'Open',
    degreeAttributes: 'Communication',
  },
  {
    year: 2024,
    term: 'Spring',
    yearTerm: '2024-sp',
    subject: 'EDUC',
    courseNumber: 450,
    courseId: 'EDUC450',
    section: '03',
    title: 'Educational Technology',
    description:
      'Educational Technology. Explores historical context and contemporary applications.',
    creditHours: '4',
    format: 'Studio',
    meetingDays: 'TR',
    startTime: '14:00',
    endTime: '15:50',
    location: 'Hollister Hall 296',
    instructor: 'Morgan Walker',
    capacity: 60,
    enrolled: 2,
    status: 'Open',
    degreeAttributes: 'Ethics; Quantitative Reasoning',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'PHIL',
    courseNumber: 120,
    courseId: 'PHIL120',
    section: '03',
    title: 'Ethics',
    description: 'Ethics. Covers foundational theory and practical techniques.',
    creditHours: '1',
    format: 'Studio',
    meetingDays: 'TR',
    startTime: '16:00',
    endTime: '17:50',
    location: 'Statler Hall 435',
    instructor: 'Taylor Patel',
    capacity: 75,
    enrolled: 33,
    status: 'Open',
    degreeAttributes: 'Social Science; Ethics',
  },
  {
    year: 2026,
    term: 'Summer',
    yearTerm: '2026-su',
    subject: 'ARCH',
    courseNumber: 370,
    courseId: 'ARCH370',
    section: '01',
    title: 'Building Systems',
    description:
      'Building Systems. Introduces core concepts with hands-on exercises.',
    creditHours: '2',
    format: 'Lecture',
    meetingDays: 'MWF',
    startTime: '13:00',
    endTime: '14:50',
    location: 'Statler Hall 150',
    instructor: 'Rowan Anderson',
    capacity: 25,
    enrolled: 14,
    status: 'Open',
    degreeAttributes: 'Humanities',
  },
  {
    year: 2025,
    term: 'Fall',
    yearTerm: '2025-fa',
    subject: 'ANTH',
    courseNumber: 350,
    courseId: 'ANTH350',
    section: '04',
    title: 'Cultural Anthropology',
    description:
      'Cultural Anthropology. Includes case studies and small-group activities.',
    creditHours: '1-3',
    format: 'Seminar',
    meetingDays: 'TR',
    startTime: '15:00',
    endTime: '15:50',
    location: 'Morrill Hall 412',
    instructor: 'Hayden Brown',
    capacity: 120,
    enrolled: 87,
    status: 'Open',
    degreeAttributes: 'Natural Science; Social Science',
  },
  {
    year: 2026,
    term: 'Spring',
    yearTerm: '2026-sp',
    subject: 'LING',
    courseNumber: 300,
    courseId: 'LING300',
    section: '04',
    title: 'Syntax',
    description:
      'Syntax. Students complete a final project demonstrating key skills.',
    creditHours: '1-3',
    format: 'Hybrid',
    meetingDays: 'M',
    startTime: '11:00',
    endTime: '12:15',
    location: 'Hollister Hall 253',
    instructor: 'Parker Brown',
    capacity: 40,
    enrolled: 29,
    status: 'Open',
    degreeAttributes: 'Ethics',
  },
  {
    year: 2025,
    term: 'Fall',
    yearTerm: '2025-fa',
    subject: 'PHYS',
    courseNumber: 490,
    courseId: 'PHYS490',
    section: '03',
    title: 'Quantum Concepts',
    description:
      'Quantum Concepts. Focuses on methods, tools, and ethical practice.',
    creditHours: '1',
    format: 'Lab',
    meetingDays: 'R',
    startTime: '15:30',
    endTime: '16:20',
    location: 'Baker Hall 410',
    instructor: 'Drew Lee',
    capacity: 40,
    enrolled: 14,
    status: 'Open',
    degreeAttributes: 'Quantitative Reasoning',
  },
  {
    year: 2025,
    term: 'Summer',
    yearTerm: '2025-su',
    subject: 'MATH',
    courseNumber: 100,
    courseId: 'MATH100',
    section: '03',
    title: 'Probability',
    description:
      'Probability. Covers foundational theory and practical techniques.',
    creditHours: '1-3',
    format: 'Lecture',
    meetingDays: 'M',
    startTime: '14:00',
    endTime: '14:50',
    location: 'Goldwin Smith 482',
    instructor: 'Quinn Garcia',
    capacity: 35,
    enrolled: 8,
    status: 'Open',
    degreeAttributes: 'Natural Science',
  },
  {
    year: 2025,
    term: 'Spring',
    yearTerm: '2025-sp',
    subject: 'ECON',
    courseNumber: 170,
    courseId: 'ECON170',
    section: '01',
    title: 'Macroeconomics',
    description:
      'Macroeconomics. Explores historical context and contemporary applications.',
    creditHours: '3-4',
    format: 'Seminar',
    meetingDays: 'W',
    startTime: '15:30',
    endTime: '16:20',
    location: 'Baker Hall 235',
    instructor: 'Jamie Patel',
    capacity: 75,
    enrolled: 47,
    status: 'Open',
    degreeAttributes: 'Diversity & Inclusion; Humanities',
  },
  {
    year: 2024,
    term: 'Spring',
    yearTerm: '2024-sp',
    subject: 'CS',
    courseNumber: 580,
    courseId: 'CS580',
    section: '03',
    title: 'Graduate Advanced Databases',
    description:
      'Graduate Advanced Databases. Includes case studies and small-group activities.',
    creditHours: '3-4',
    format: 'Studio',
    meetingDays: 'TR',
    startTime: '13:30',
    endTime: '14:20',
    location: 'Baker Hall 119',
    instructor: 'Casey Lee',
    capacity: 25,
    enrolled: 3,
    status: 'Open',
    degreeAttributes: 'Ethics',
  },
  {
    year: 2025,
    term: 'Summer',
    yearTerm: '2025-su',
    subject: 'EDUC',
    courseNumber: 490,
    courseId: 'EDUC490',
    section: '02',
    title: 'Curriculum Design',
    description:
      'Curriculum Design. Includes case studies and small-group activities.',
    creditHours: '1-3',
    format: 'Studio',
    meetingDays: 'M',
    startTime: '15:30',
    endTime: '16:20',
    location: 'Sage Hall 327',
    instructor: 'Cameron Kim',
    capacity: 45,
    enrolled: 6,
    status: 'Open',
    degreeAttributes: 'Humanities',
  },
  {
    year: 2025,
    term: 'Fall',
    yearTerm: '2025-fa',
    subject: 'CHEM',
    courseNumber: 410,
    courseId: 'CHEM410',
    section: '02',
    title: 'Advanced Organic Chemistry',
    description:
      'Advanced Organic Chemistry. Covers foundational theory and practical techniques.',
    creditHours: '2',
    format: 'Lab',
    meetingDays: 'R',
    startTime: '11:00',
    endTime: '11:50',
    location: 'Sage Hall 400',
    instructor: 'Morgan Walker',
    capacity: 35,
    enrolled: 21,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2024,
    term: 'Fall',
    yearTerm: '2024-fa',
    subject: 'EDUC',
    courseNumber: 320,
    courseId: 'EDUC320',
    section: '01',
    title: 'Educational Technology',
    description:
      'Educational Technology. Explores historical context and contemporary applications.',
    creditHours: '2',
    format: 'Lecture',
    meetingDays: 'R',
    startTime: '09:30',
    endTime: '10:20',
    location: 'Goldwin Smith 108',
    instructor: 'Taylor Smith',
    capacity: 20,
    enrolled: 4,
    status: 'Closed',
    degreeAttributes: '',
  },
  {
    year: 2024,
    term: 'Spring',
    yearTerm: '2024-sp',
    subject: 'LING',
    courseNumber: 380,
    courseId: 'LING380',
    section: '01',
    title: 'Syntax',
    description: 'Syntax. Introduces core concepts with hands-on exercises.',
    creditHours: '2',
    format: 'Online',
    meetingDays: 'MWF',
    startTime: '09:30',
    endTime: '10:45',
    location: 'Baker Hall 345',
    instructor: 'Hayden Brown',
    capacity: 60,
    enrolled: 43,
    status: 'Open',
    degreeAttributes: 'Communication; Humanities',
  },
  {
    year: 2025,
    term: 'Summer',
    yearTerm: '2025-su',
    subject: 'MATH',
    courseNumber: 120,
    courseId: 'MATH120',
    section: '03',
    title: 'Differential Equations',
    description:
      'Differential Equations. Includes case studies and small-group activities.',
    creditHours: '1-3',
    format: 'Hybrid',
    meetingDays: 'R',
    startTime: '14:30',
    endTime: '16:20',
    location: 'Uris Hall 332',
    instructor: 'Jamie Wilson',
    capacity: 60,
    enrolled: 6,
    status: 'Open',
    degreeAttributes: 'Ethics',
  },
  {
    year: 2024,
    term: 'Spring',
    yearTerm: '2024-sp',
    subject: 'ECON',
    courseNumber: 460,
    courseId: 'ECON460',
    section: '04',
    title: 'Advanced Microeconomics',
    description:
      'Advanced Microeconomics. Focuses on methods, tools, and ethical practice.',
    creditHours: '3-4',
    format: 'Lab',
    meetingDays: 'W',
    startTime: '13:30',
    endTime: '14:20',
    location: 'Morrill Hall 146',
    instructor: 'Hayden Patel',
    capacity: 25,
    enrolled: 13,
    status: 'Open',
    degreeAttributes: 'Natural Science',
  },
  {
    year: 2024,
    term: 'Summer',
    yearTerm: '2024-su',
    subject: 'EDUC',
    courseNumber: 550,
    courseId: 'EDUC550',
    section: '01',
    title: 'Curriculum Design',
    description:
      'Curriculum Design. Covers foundational theory and practical techniques.',
    creditHours: '3-4',
    format: 'Studio',
    meetingDays: 'M',
    startTime: '09:30',
    endTime: '11:20',
    location: 'Goldwin Smith 153',
    instructor: 'Skyler Martinez',
    capacity: 35,
    enrolled: 9,
    status: 'Closed',
    degreeAttributes: 'Social Science',
  },
  {
    year: 2026,
    term: 'Spring',
    yearTerm: '2026-sp',
    subject: 'CHEM',
    courseNumber: 390,
    courseId: 'CHEM390',
    section: '02',
    title: 'Physical Chemistry',
    description:
      'Physical Chemistry. Focuses on methods, tools, and ethical practice.',
    creditHours: '1-3',
    format: 'Online',
    meetingDays: 'TR',
    startTime: '09:30',
    endTime: '10:20',
    location: 'Uris Hall 459',
    instructor: 'Rowan Smith',
    capacity: 45,
    enrolled: 22,
    status: 'Open',
    degreeAttributes: 'Natural Science',
  },
  {
    year: 2026,
    term: 'Spring',
    yearTerm: '2026-sp',
    subject: 'BIOL',
    courseNumber: 200,
    courseId: 'BIOL200',
    section: '01',
    title: 'Microbiology',
    description:
      'Microbiology. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '4',
    format: 'Seminar',
    meetingDays: 'TR',
    startTime: '15:30',
    endTime: '16:45',
    location: 'Goldwin Smith 259',
    instructor: 'Drew Johnson',
    capacity: 120,
    enrolled: 76,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2024,
    term: 'Summer',
    yearTerm: '2024-su',
    subject: 'HIST',
    courseNumber: 140,
    courseId: 'HIST140',
    section: '04',
    title: 'History of Science',
    description:
      'History of Science. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '1-3',
    format: 'Studio',
    meetingDays: 'TR',
    startTime: '16:30',
    endTime: '17:45',
    location: 'Tjaden Hall 158',
    instructor: 'Riley Brown',
    capacity: 25,
    enrolled: 9,
    status: 'Closed',
    degreeAttributes: 'Humanities',
  },
  {
    year: 2025,
    term: 'Summer',
    yearTerm: '2025-su',
    subject: 'HIST',
    courseNumber: 130,
    courseId: 'HIST130',
    section: '03',
    title: 'Modern Europe',
    description:
      'Modern Europe. Includes case studies and small-group activities.',
    creditHours: '3',
    format: 'Seminar',
    meetingDays: 'MWF',
    startTime: '13:30',
    endTime: '14:20',
    location: 'Phillips Hall 482',
    instructor: 'Quinn Garcia',
    capacity: 30,
    enrolled: 12,
    status: 'Open',
    degreeAttributes: 'Social Science',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'STAT',
    courseNumber: 170,
    courseId: 'STAT170',
    section: '01',
    title: 'Statistical Computing',
    description:
      'Statistical Computing. Includes case studies and small-group activities.',
    creditHours: '4',
    format: 'Online',
    meetingDays: 'MWF',
    startTime: '15:30',
    endTime: '16:45',
    location: 'Statler Hall 110',
    instructor: 'Riley Garcia',
    capacity: 120,
    enrolled: 58,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2024,
    term: 'Fall',
    yearTerm: '2024-fa',
    subject: 'STAT',
    courseNumber: 560,
    courseId: 'STAT560',
    section: '01',
    title: 'Statistical Computing',
    description:
      'Statistical Computing. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '3',
    format: 'Seminar',
    meetingDays: 'MWF',
    startTime: '11:00',
    endTime: '12:50',
    location: 'Tjaden Hall 361',
    instructor: 'Morgan Lewis',
    capacity: 45,
    enrolled: 22,
    status: 'Open',
    degreeAttributes: 'Social Science',
  },
  {
    year: 2025,
    term: 'Fall',
    yearTerm: '2025-fa',
    subject: 'ART',
    courseNumber: 520,
    courseId: 'ART520',
    section: '01',
    title: 'Drawing',
    description:
      'Drawing. Covers foundational theory and practical techniques.',
    creditHours: '1-3',
    format: 'Studio',
    meetingDays: 'M',
    startTime: '16:30',
    endTime: '18:20',
    location: 'Olin Library 325',
    instructor: 'Jordan Lee',
    capacity: 75,
    enrolled: 38,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'ANTH',
    courseNumber: 470,
    courseId: 'ANTH470',
    section: '01',
    title: 'Cultural Anthropology',
    description:
      'Cultural Anthropology. Focuses on methods, tools, and ethical practice.',
    creditHours: '1',
    format: 'Lab',
    meetingDays: 'R',
    startTime: '10:30',
    endTime: '11:45',
    location: 'Tjaden Hall 478',
    instructor: 'Avery Lee',
    capacity: 120,
    enrolled: 83,
    status: 'Open',
    degreeAttributes: 'Communication',
  },
  {
    year: 2024,
    term: 'Fall',
    yearTerm: '2024-fa',
    subject: 'LING',
    courseNumber: 150,
    courseId: 'LING150',
    section: '01',
    title: 'Sociolinguistics',
    description:
      'Sociolinguistics. Includes case studies and small-group activities.',
    creditHours: '2',
    format: 'Hybrid',
    meetingDays: 'W',
    startTime: '09:00',
    endTime: '10:50',
    location: 'Phillips Hall 368',
    instructor: 'Jamie Wilson',
    capacity: 30,
    enrolled: 11,
    status: 'Open',
    degreeAttributes: 'Ethics',
  },
  {
    year: 2025,
    term: 'Summer',
    yearTerm: '2025-su',
    subject: 'THEA',
    courseNumber: 150,
    courseId: 'THEA150',
    section: '01',
    title: 'Stagecraft',
    description:
      'Stagecraft. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '1-3',
    format: 'Lecture',
    meetingDays: 'R',
    startTime: '15:30',
    endTime: '16:45',
    location: 'Olin Library 270',
    instructor: 'Jordan Wilson',
    capacity: 30,
    enrolled: 29,
    status: 'Open',
    degreeAttributes: 'Ethics',
  },
  {
    year: 2026,
    term: 'Summer',
    yearTerm: '2026-su',
    subject: 'BIOL',
    courseNumber: 380,
    courseId: 'BIOL380',
    section: '04',
    title: 'Ecology',
    description:
      'Ecology. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '3-4',
    format: 'Seminar',
    meetingDays: 'M',
    startTime: '10:30',
    endTime: '12:20',
    location: 'Baker Hall 285',
    instructor: 'Casey Garcia',
    capacity: 35,
    enrolled: 21,
    status: 'Closed',
    degreeAttributes: 'Quantitative Reasoning',
  },
  {
    year: 2024,
    term: 'Fall',
    yearTerm: '2024-fa',
    subject: 'ANTH',
    courseNumber: 180,
    courseId: 'ANTH180',
    section: '01',
    title: 'Human Origins',
    description:
      'Human Origins. Includes case studies and small-group activities.',
    creditHours: '1-3',
    format: 'Lab',
    meetingDays: 'TR',
    startTime: '11:30',
    endTime: '12:20',
    location: 'Olin Library 454',
    instructor: 'Rowan Wilson',
    capacity: 30,
    enrolled: 23,
    status: 'Closed',
    degreeAttributes: '',
  },
  {
    year: 2025,
    term: 'Summer',
    yearTerm: '2025-su',
    subject: 'PHYS',
    courseNumber: 490,
    courseId: 'PHYS490',
    section: '03',
    title: 'Advanced Astrophysics',
    description:
      'Advanced Astrophysics. Students complete a final project demonstrating key skills.',
    creditHours: '3',
    format: 'Seminar',
    meetingDays: 'R',
    startTime: '16:00',
    endTime: '17:15',
    location: 'Phillips Hall 336',
    instructor: 'Rowan Smith',
    capacity: 60,
    enrolled: 32,
    status: 'Closed',
    degreeAttributes: 'Quantitative Reasoning',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'ENGL',
    courseNumber: 170,
    courseId: 'ENGL170',
    section: '03',
    title: 'Creative Writing',
    description:
      'Creative Writing. Includes case studies and small-group activities.',
    creditHours: '1-3',
    format: 'Hybrid',
    meetingDays: 'TR',
    startTime: '10:30',
    endTime: '11:20',
    location: 'Uris Hall 330',
    instructor: 'Jamie Garcia',
    capacity: 60,
    enrolled: 5,
    status: 'Open',
    degreeAttributes: 'Diversity & Inclusion; Humanities',
  },
  {
    year: 2024,
    term: 'Spring',
    yearTerm: '2024-sp',
    subject: 'GEOG',
    courseNumber: 330,
    courseId: 'GEOG330',
    section: '04',
    title: 'Human Geography',
    description:
      'Human Geography. Introduces core concepts with hands-on exercises.',
    creditHours: '2',
    format: 'Lab',
    meetingDays: 'M',
    startTime: '09:30',
    endTime: '10:20',
    location: 'Olin Library 170',
    instructor: 'Avery Smith',
    capacity: 75,
    enrolled: 17,
    status: 'Closed',
    degreeAttributes: 'Humanities; Communication',
  },
  {
    year: 2025,
    term: 'Fall',
    yearTerm: '2025-fa',
    subject: 'MATH',
    courseNumber: 590,
    courseId: 'MATH590',
    section: '04',
    title: 'Graduate Calculus',
    description:
      'Graduate Calculus. Covers foundational theory and practical techniques.',
    creditHours: '1',
    format: 'Lecture',
    meetingDays: 'R',
    startTime: '12:30',
    endTime: '14:20',
    location: 'Phillips Hall 132',
    instructor: 'Jordan Walker',
    capacity: 75,
    enrolled: 68,
    status: 'Open',
    degreeAttributes: 'Natural Science',
  },
  {
    year: 2025,
    term: 'Fall',
    yearTerm: '2025-fa',
    subject: 'THEA',
    courseNumber: 330,
    courseId: 'THEA330',
    section: '04',
    title: 'Acting',
    description: 'Acting. Includes case studies and small-group activities.',
    creditHours: '3-4',
    format: 'Hybrid',
    meetingDays: 'R',
    startTime: '10:30',
    endTime: '11:20',
    location: 'Tjaden Hall 359',
    instructor: 'Rowan Martinez',
    capacity: 100,
    enrolled: 2,
    status: 'Closed',
    degreeAttributes: 'Humanities; Diversity & Inclusion',
  },
  {
    year: 2025,
    term: 'Spring',
    yearTerm: '2025-sp',
    subject: 'CS',
    courseNumber: 310,
    courseId: 'CS310',
    section: '03',
    title: 'Software Design',
    description:
      'Software Design. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '3-4',
    format: 'Hybrid',
    meetingDays: 'MWF',
    startTime: '10:30',
    endTime: '11:20',
    location: 'Goldwin Smith 379',
    instructor: 'Riley Walker',
    capacity: 30,
    enrolled: 26,
    status: 'Closed',
    degreeAttributes: 'Natural Science; Ethics',
  },
  {
    year: 2024,
    term: 'Summer',
    yearTerm: '2024-su',
    subject: 'LING',
    courseNumber: 140,
    courseId: 'LING140',
    section: '02',
    title: 'Phonetics',
    description:
      'Phonetics. Students complete a final project demonstrating key skills.',
    creditHours: '1',
    format: 'Seminar',
    meetingDays: 'W',
    startTime: '14:30',
    endTime: '16:20',
    location: 'Tjaden Hall 342',
    instructor: 'Casey Nguyen',
    capacity: 35,
    enrolled: 18,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2026,
    term: 'Spring',
    yearTerm: '2026-sp',
    subject: 'ENGL',
    courseNumber: 150,
    courseId: 'ENGL150',
    section: '04',
    title: 'Technical Writing',
    description:
      'Technical Writing. Includes case studies and small-group activities.',
    creditHours: '4',
    format: 'Hybrid',
    meetingDays: 'W',
    startTime: '15:30',
    endTime: '16:20',
    location: 'Phillips Hall 288',
    instructor: 'Rowan Martinez',
    capacity: 40,
    enrolled: 5,
    status: 'Closed',
    degreeAttributes: '',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'EDUC',
    courseNumber: 350,
    courseId: 'EDUC350',
    section: '01',
    title: 'Learning Sciences',
    description:
      'Learning Sciences. Covers foundational theory and practical techniques.',
    creditHours: '3-4',
    format: 'Lab',
    meetingDays: 'R',
    startTime: '13:30',
    endTime: '14:45',
    location: 'Statler Hall 185',
    instructor: 'Drew Lee',
    capacity: 45,
    enrolled: 28,
    status: 'Open',
    degreeAttributes: 'Ethics',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'BIOL',
    courseNumber: 450,
    courseId: 'BIOL450',
    section: '02',
    title: 'Advanced Cell Biology',
    description:
      'Advanced Cell Biology. Covers foundational theory and practical techniques.',
    creditHours: '3-4',
    format: 'Online',
    meetingDays: 'MWF',
    startTime: '16:00',
    endTime: '16:50',
    location: 'Sage Hall 498',
    instructor: 'Parker Johnson',
    capacity: 45,
    enrolled: 24,
    status: 'Open',
    degreeAttributes: 'Communication',
  },
  {
    year: 2025,
    term: 'Spring',
    yearTerm: '2025-sp',
    subject: 'BIOL',
    courseNumber: 520,
    courseId: 'BIOL520',
    section: '03',
    title: 'Advanced Evolution',
    description:
      'Advanced Evolution. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '1',
    format: 'Lecture',
    meetingDays: 'W',
    startTime: '11:30',
    endTime: '13:20',
    location: 'Tjaden Hall 160',
    instructor: 'Casey Lewis',
    capacity: 40,
    enrolled: 28,
    status: 'Open',
    degreeAttributes: 'Communication',
  },
  {
    year: 2024,
    term: 'Fall',
    yearTerm: '2024-fa',
    subject: 'BIOL',
    courseNumber: 420,
    courseId: 'BIOL420',
    section: '04',
    title: 'Cell Biology',
    description:
      'Cell Biology. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '3-4',
    format: 'Lab',
    meetingDays: 'R',
    startTime: '14:00',
    endTime: '15:50',
    location: 'Uris Hall 253',
    instructor: 'Hayden Garcia',
    capacity: 30,
    enrolled: 25,
    status: 'Open',
    degreeAttributes: 'Social Science',
  },
  {
    year: 2024,
    term: 'Fall',
    yearTerm: '2024-fa',
    subject: 'PHIL',
    courseNumber: 150,
    courseId: 'PHIL150',
    section: '03',
    title: 'Logic',
    description:
      'Logic. Explores historical context and contemporary applications.',
    creditHours: '2',
    format: 'Online',
    meetingDays: 'W',
    startTime: '10:00',
    endTime: '11:15',
    location: 'Phillips Hall 369',
    instructor: 'Quinn Lewis',
    capacity: 60,
    enrolled: 52,
    status: 'Open',
    degreeAttributes: 'Diversity & Inclusion',
  },
  {
    year: 2024,
    term: 'Spring',
    yearTerm: '2024-sp',
    subject: 'LING',
    courseNumber: 550,
    courseId: 'LING550',
    section: '02',
    title: 'Graduate Sociolinguistics',
    description:
      'Graduate Sociolinguistics. Covers foundational theory and practical techniques.',
    creditHours: '4',
    format: 'Seminar',
    meetingDays: 'TR',
    startTime: '09:00',
    endTime: '10:50',
    location: 'Uris Hall 184',
    instructor: 'Taylor Johnson',
    capacity: 35,
    enrolled: 22,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2024,
    term: 'Summer',
    yearTerm: '2024-su',
    subject: 'EDUC',
    courseNumber: 320,
    courseId: 'EDUC320',
    section: '03',
    title: 'Educational Technology',
    description:
      'Educational Technology. Explores historical context and contemporary applications.',
    creditHours: '1',
    format: 'Online',
    meetingDays: 'R',
    startTime: '11:00',
    endTime: '11:50',
    location: 'Hollister Hall 272',
    instructor: 'Hayden Wilson',
    capacity: 20,
    enrolled: 0,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2026,
    term: 'Spring',
    yearTerm: '2026-sp',
    subject: 'MUS',
    courseNumber: 560,
    courseId: 'MUS560',
    section: '01',
    title: 'Performance Workshop',
    description:
      'Performance Workshop. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '3',
    format: 'Hybrid',
    meetingDays: 'W',
    startTime: '16:00',
    endTime: '17:50',
    location: 'Uris Hall 332',
    instructor: 'Jordan Clark',
    capacity: 20,
    enrolled: 5,
    status: 'Closed',
    degreeAttributes: 'Communication; Quantitative Reasoning',
  },
  {
    year: 2025,
    term: 'Summer',
    yearTerm: '2025-su',
    subject: 'MATH',
    courseNumber: 350,
    courseId: 'MATH350',
    section: '03',
    title: 'Probability',
    description:
      'Probability. Students complete a final project demonstrating key skills.',
    creditHours: '3',
    format: 'Seminar',
    meetingDays: 'W',
    startTime: '10:30',
    endTime: '11:20',
    location: 'Morrill Hall 236',
    instructor: 'Cameron Kim',
    capacity: 30,
    enrolled: 3,
    status: 'Open',
    degreeAttributes: 'Ethics',
  },
  {
    year: 2026,
    term: 'Spring',
    yearTerm: '2026-sp',
    subject: 'PHYS',
    courseNumber: 250,
    courseId: 'PHYS250',
    section: '03',
    title: 'Electricity and Magnetism',
    description:
      'Electricity and Magnetism. Introduces core concepts with hands-on exercises.',
    creditHours: '4',
    format: 'Seminar',
    meetingDays: 'W',
    startTime: '16:30',
    endTime: '17:45',
    location: 'Baker Hall 146',
    instructor: 'Quinn Martinez',
    capacity: 75,
    enrolled: 30,
    status: 'Open',
    degreeAttributes: 'Humanities',
  },
  {
    year: 2025,
    term: 'Spring',
    yearTerm: '2025-sp',
    subject: 'THEA',
    courseNumber: 440,
    courseId: 'THEA440',
    section: '01',
    title: 'Acting',
    description: 'Acting. Includes case studies and small-group activities.',
    creditHours: '3-4',
    format: 'Lab',
    meetingDays: 'MWF',
    startTime: '14:30',
    endTime: '15:45',
    location: 'Statler Hall 126',
    instructor: 'Skyler Martinez',
    capacity: 35,
    enrolled: 23,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2026,
    term: 'Spring',
    yearTerm: '2026-sp',
    subject: 'EDUC',
    courseNumber: 390,
    courseId: 'EDUC390',
    section: '01',
    title: 'Learning Sciences',
    description:
      'Learning Sciences. Introduces core concepts with hands-on exercises.',
    creditHours: '4',
    format: 'Lecture',
    meetingDays: 'M',
    startTime: '14:30',
    endTime: '16:20',
    location: 'Olin Library 201',
    instructor: 'Skyler Martinez',
    capacity: 60,
    enrolled: 32,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2024,
    term: 'Summer',
    yearTerm: '2024-su',
    subject: 'ECON',
    courseNumber: 480,
    courseId: 'ECON480',
    section: '04',
    title: 'Macroeconomics',
    description:
      'Macroeconomics. Students complete a final project demonstrating key skills.',
    creditHours: '2',
    format: 'Online',
    meetingDays: 'W',
    startTime: '14:30',
    endTime: '15:20',
    location: 'Hollister Hall 478',
    instructor: 'Hayden Smith',
    capacity: 120,
    enrolled: 43,
    status: 'Closed',
    degreeAttributes: 'Communication',
  },
  {
    year: 2024,
    term: 'Spring',
    yearTerm: '2024-sp',
    subject: 'ECON',
    courseNumber: 160,
    courseId: 'ECON160',
    section: '03',
    title: 'Microeconomics',
    description:
      'Microeconomics. Introduces core concepts with hands-on exercises.',
    creditHours: '4',
    format: 'Online',
    meetingDays: 'MWF',
    startTime: '13:00',
    endTime: '14:50',
    location: 'Hollister Hall 345',
    instructor: 'Taylor Martinez',
    capacity: 120,
    enrolled: 99,
    status: 'Closed',
    degreeAttributes: 'Quantitative Reasoning',
  },
  {
    year: 2026,
    term: 'Summer',
    yearTerm: '2026-su',
    subject: 'CHEM',
    courseNumber: 200,
    courseId: 'CHEM200',
    section: '04',
    title: 'Biochemistry',
    description:
      'Biochemistry. Focuses on methods, tools, and ethical practice.',
    creditHours: '2',
    format: 'Studio',
    meetingDays: 'R',
    startTime: '15:00',
    endTime: '16:15',
    location: 'Hollister Hall 341',
    instructor: 'Hayden Walker',
    capacity: 20,
    enrolled: 4,
    status: 'Open',
    degreeAttributes: 'Communication',
  },
  {
    year: 2025,
    term: 'Spring',
    yearTerm: '2025-sp',
    subject: 'ART',
    courseNumber: 480,
    courseId: 'ART480',
    section: '03',
    title: 'Design Fundamentals',
    description:
      'Design Fundamentals. Covers foundational theory and practical techniques.',
    creditHours: '3-4',
    format: 'Hybrid',
    meetingDays: 'TR',
    startTime: '13:30',
    endTime: '14:20',
    location: 'Uris Hall 385',
    instructor: 'Casey Kim',
    capacity: 40,
    enrolled: 18,
    status: 'Open',
    degreeAttributes: 'Diversity & Inclusion; Quantitative Reasoning',
  },
  {
    year: 2026,
    term: 'Summer',
    yearTerm: '2026-su',
    subject: 'ENGL',
    courseNumber: 310,
    courseId: 'ENGL310',
    section: '04',
    title: 'Technical Writing',
    description:
      'Technical Writing. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '2',
    format: 'Lab',
    meetingDays: 'MWF',
    startTime: '13:00',
    endTime: '14:15',
    location: 'Goldwin Smith 326',
    instructor: 'Parker Smith',
    capacity: 75,
    enrolled: 27,
    status: 'Open',
    degreeAttributes: 'Writing Intensive',
  },
  {
    year: 2024,
    term: 'Summer',
    yearTerm: '2024-su',
    subject: 'INFO',
    courseNumber: 230,
    courseId: 'INFO230',
    section: '01',
    title: 'Information Policy',
    description:
      'Information Policy. Explores historical context and contemporary applications.',
    creditHours: '2',
    format: 'Online',
    meetingDays: 'W',
    startTime: '12:00',
    endTime: '12:50',
    location: 'Goldwin Smith 467',
    instructor: 'Cameron Patel',
    capacity: 30,
    enrolled: 0,
    status: 'Open',
    degreeAttributes: 'Communication; Quantitative Reasoning',
  },
  {
    year: 2024,
    term: 'Spring',
    yearTerm: '2024-sp',
    subject: 'ECON',
    courseNumber: 300,
    courseId: 'ECON300',
    section: '01',
    title: 'Macroeconomics',
    description:
      'Macroeconomics. Introduces core concepts with hands-on exercises.',
    creditHours: '3-4',
    format: 'Online',
    meetingDays: 'TR',
    startTime: '09:00',
    endTime: '10:15',
    location: 'Baker Hall 303',
    instructor: 'Rowan Lee',
    capacity: 30,
    enrolled: 29,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2025,
    term: 'Summer',
    yearTerm: '2025-su',
    subject: 'THEA',
    courseNumber: 150,
    courseId: 'THEA150',
    section: '03',
    title: 'Stagecraft',
    description:
      'Stagecraft. Introduces core concepts with hands-on exercises.',
    creditHours: '1-3',
    format: 'Hybrid',
    meetingDays: 'W',
    startTime: '16:00',
    endTime: '17:50',
    location: 'Uris Hall 198',
    instructor: 'Rowan Patel',
    capacity: 45,
    enrolled: 10,
    status: 'Closed',
    degreeAttributes: 'Natural Science',
  },
  {
    year: 2026,
    term: 'Spring',
    yearTerm: '2026-sp',
    subject: 'ANTH',
    courseNumber: 530,
    courseId: 'ANTH530',
    section: '02',
    title: 'Human Origins',
    description:
      'Human Origins. Students complete a final project demonstrating key skills.',
    creditHours: '1-3',
    format: 'Studio',
    meetingDays: 'MWF',
    startTime: '14:00',
    endTime: '15:15',
    location: 'Olin Library 171',
    instructor: 'Cameron Johnson',
    capacity: 35,
    enrolled: 0,
    status: 'Open',
    degreeAttributes: 'Quantitative Reasoning; Communication',
  },
  {
    year: 2025,
    term: 'Spring',
    yearTerm: '2025-sp',
    subject: 'ANTH',
    courseNumber: 590,
    courseId: 'ANTH590',
    section: '01',
    title: 'Archaeology',
    description:
      'Archaeology. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '3-4',
    format: 'Lecture',
    meetingDays: 'TR',
    startTime: '10:30',
    endTime: '11:45',
    location: 'Statler Hall 451',
    instructor: 'Jamie Clark',
    capacity: 40,
    enrolled: 7,
    status: 'Open',
    degreeAttributes: 'Quantitative Reasoning',
  },
  {
    year: 2024,
    term: 'Spring',
    yearTerm: '2024-sp',
    subject: 'MATH',
    courseNumber: 490,
    courseId: 'MATH490',
    section: '03',
    title: 'Probability',
    description:
      'Probability. Students complete a final project demonstrating key skills.',
    creditHours: '1-3',
    format: 'Studio',
    meetingDays: 'R',
    startTime: '12:00',
    endTime: '13:50',
    location: 'Morrill Hall 369',
    instructor: 'Cameron Martinez',
    capacity: 45,
    enrolled: 4,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2026,
    term: 'Summer',
    yearTerm: '2026-su',
    subject: 'MUS',
    courseNumber: 580,
    courseId: 'MUS580',
    section: '02',
    title: 'Advanced Composition',
    description:
      'Advanced Composition. Focuses on methods, tools, and ethical practice.',
    creditHours: '3-4',
    format: 'Lecture',
    meetingDays: 'R',
    startTime: '12:30',
    endTime: '13:20',
    location: 'Phillips Hall 128',
    instructor: 'Cameron Garcia',
    capacity: 100,
    enrolled: 53,
    status: 'Closed',
    degreeAttributes: '',
  },
  {
    year: 2025,
    term: 'Summer',
    yearTerm: '2025-su',
    subject: 'ANTH',
    courseNumber: 160,
    courseId: 'ANTH160',
    section: '03',
    title: 'Cultural Anthropology',
    description:
      'Cultural Anthropology. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '2',
    format: 'Hybrid',
    meetingDays: 'M',
    startTime: '10:00',
    endTime: '11:15',
    location: 'Morrill Hall 377',
    instructor: 'Avery Patel',
    capacity: 75,
    enrolled: 4,
    status: 'Open',
    degreeAttributes: 'Natural Science; Ethics',
  },
  {
    year: 2026,
    term: 'Summer',
    yearTerm: '2026-su',
    subject: 'STAT',
    courseNumber: 360,
    courseId: 'STAT360',
    section: '04',
    title: 'Statistical Computing',
    description:
      'Statistical Computing. Explores historical context and contemporary applications.',
    creditHours: '1',
    format: 'Studio',
    meetingDays: 'TR',
    startTime: '11:30',
    endTime: '12:20',
    location: 'Tjaden Hall 301',
    instructor: 'Jamie Garcia',
    capacity: 35,
    enrolled: 0,
    status: 'Open',
    degreeAttributes: 'Communication',
  },
  {
    year: 2026,
    term: 'Summer',
    yearTerm: '2026-su',
    subject: 'STAT',
    courseNumber: 560,
    courseId: 'STAT560',
    section: '02',
    title: 'Graduate Applied Statistics',
    description:
      'Graduate Applied Statistics. Includes case studies and small-group activities.',
    creditHours: '3-4',
    format: 'Seminar',
    meetingDays: 'W',
    startTime: '10:00',
    endTime: '11:50',
    location: 'Hollister Hall 492',
    instructor: 'Avery Kim',
    capacity: 35,
    enrolled: 4,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2026,
    term: 'Summer',
    yearTerm: '2026-su',
    subject: 'HIST',
    courseNumber: 200,
    courseId: 'HIST200',
    section: '04',
    title: 'History of Science',
    description:
      'History of Science. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '1-3',
    format: 'Seminar',
    meetingDays: 'R',
    startTime: '12:00',
    endTime: '12:50',
    location: 'Uris Hall 219',
    instructor: 'Hayden Clark',
    capacity: 120,
    enrolled: 40,
    status: 'Open',
    degreeAttributes: 'Writing Intensive',
  },
  {
    year: 2026,
    term: 'Summer',
    yearTerm: '2026-su',
    subject: 'PHYS',
    courseNumber: 440,
    courseId: 'PHYS440',
    section: '03',
    title: 'Mechanics',
    description:
      'Mechanics. Covers foundational theory and practical techniques.',
    creditHours: '3-4',
    format: 'Online',
    meetingDays: 'W',
    startTime: '11:30',
    endTime: '13:20',
    location: 'Baker Hall 276',
    instructor: 'Parker Anderson',
    capacity: 60,
    enrolled: 50,
    status: 'Open',
    degreeAttributes: 'Ethics; Social Science',
  },
  {
    year: 2025,
    term: 'Fall',
    yearTerm: '2025-fa',
    subject: 'EDUC',
    courseNumber: 430,
    courseId: 'EDUC430',
    section: '02',
    title: 'Curriculum Design',
    description:
      'Curriculum Design. Includes case studies and small-group activities.',
    creditHours: '4',
    format: 'Seminar',
    meetingDays: 'R',
    startTime: '09:30',
    endTime: '10:45',
    location: 'Tjaden Hall 168',
    instructor: 'Quinn Kim',
    capacity: 40,
    enrolled: 13,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2025,
    term: 'Fall',
    yearTerm: '2025-fa',
    subject: 'EDUC',
    courseNumber: 200,
    courseId: 'EDUC200',
    section: '03',
    title: 'Curriculum Design',
    description:
      'Curriculum Design. Explores historical context and contemporary applications.',
    creditHours: '1-3',
    format: 'Hybrid',
    meetingDays: 'R',
    startTime: '09:00',
    endTime: '09:50',
    location: 'Tjaden Hall 211',
    instructor: 'Cameron Kim',
    capacity: 45,
    enrolled: 19,
    status: 'Open',
    degreeAttributes: 'Quantitative Reasoning',
  },
  {
    year: 2024,
    term: 'Summer',
    yearTerm: '2024-su',
    subject: 'PHIL',
    courseNumber: 290,
    courseId: 'PHIL290',
    section: '02',
    title: 'Logic',
    description:
      'Logic. Explores historical context and contemporary applications.',
    creditHours: '1-3',
    format: 'Seminar',
    meetingDays: 'W',
    startTime: '14:30',
    endTime: '15:45',
    location: 'Tjaden Hall 432',
    instructor: 'Riley Smith',
    capacity: 40,
    enrolled: 23,
    status: 'Closed',
    degreeAttributes: 'Social Science; Ethics',
  },
  {
    year: 2025,
    term: 'Spring',
    yearTerm: '2025-sp',
    subject: 'MUS',
    courseNumber: 350,
    courseId: 'MUS350',
    section: '04',
    title: 'Music Theory',
    description:
      'Music Theory. Includes case studies and small-group activities.',
    creditHours: '2',
    format: 'Online',
    meetingDays: 'R',
    startTime: '11:00',
    endTime: '12:15',
    location: 'Hollister Hall 396',
    instructor: 'Drew Brown',
    capacity: 40,
    enrolled: 9,
    status: 'Open',
    degreeAttributes: 'Quantitative Reasoning',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'PHIL',
    courseNumber: 550,
    courseId: 'PHIL550',
    section: '03',
    title: 'Logic',
    description:
      'Logic. Students complete a final project demonstrating key skills.',
    creditHours: '4',
    format: 'Studio',
    meetingDays: 'TR',
    startTime: '11:30',
    endTime: '12:20',
    location: 'Tjaden Hall 350',
    instructor: 'Taylor Martinez',
    capacity: 20,
    enrolled: 16,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'CS',
    courseNumber: 420,
    courseId: 'CS420',
    section: '02',
    title: 'Data Structures',
    description:
      'Data Structures. Introduces core concepts with hands-on exercises.',
    creditHours: '2',
    format: 'Lecture',
    meetingDays: 'R',
    startTime: '16:30',
    endTime: '17:20',
    location: 'Hollister Hall 347',
    instructor: 'Parker Lee',
    capacity: 20,
    enrolled: 0,
    status: 'Closed',
    degreeAttributes: '',
  },
  {
    year: 2026,
    term: 'Summer',
    yearTerm: '2026-su',
    subject: 'ENGL',
    courseNumber: 540,
    courseId: 'ENGL540',
    section: '01',
    title: 'Technical Writing',
    description:
      'Technical Writing. Includes case studies and small-group activities.',
    creditHours: '1',
    format: 'Lecture',
    meetingDays: 'R',
    startTime: '11:00',
    endTime: '11:50',
    location: 'Tjaden Hall 229',
    instructor: 'Hayden Johnson',
    capacity: 40,
    enrolled: 25,
    status: 'Open',
    degreeAttributes: 'Ethics',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'PHYS',
    courseNumber: 310,
    courseId: 'PHYS310',
    section: '01',
    title: 'Mechanics',
    description: 'Mechanics. Focuses on methods, tools, and ethical practice.',
    creditHours: '4',
    format: 'Studio',
    meetingDays: 'MWF',
    startTime: '15:30',
    endTime: '16:20',
    location: 'Olin Library 142',
    instructor: 'Cameron Walker',
    capacity: 60,
    enrolled: 41,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2024,
    term: 'Fall',
    yearTerm: '2024-fa',
    subject: 'MUS',
    courseNumber: 570,
    courseId: 'MUS570',
    section: '03',
    title: 'Music Theory',
    description:
      'Music Theory. Focuses on methods, tools, and ethical practice.',
    creditHours: '1-3',
    format: 'Lab',
    meetingDays: 'MWF',
    startTime: '09:00',
    endTime: '10:15',
    location: 'Sage Hall 400',
    instructor: 'Taylor Lewis',
    capacity: 60,
    enrolled: 59,
    status: 'Open',
    degreeAttributes: 'Natural Science',
  },
  {
    year: 2024,
    term: 'Summer',
    yearTerm: '2024-su',
    subject: 'ARCH',
    courseNumber: 550,
    courseId: 'ARCH550',
    section: '04',
    title: 'Advanced Building Systems',
    description:
      'Advanced Building Systems. Explores historical context and contemporary applications.',
    creditHours: '1',
    format: 'Hybrid',
    meetingDays: 'W',
    startTime: '14:00',
    endTime: '14:50',
    location: 'Sage Hall 138',
    instructor: 'Riley Wilson',
    capacity: 120,
    enrolled: 76,
    status: 'Closed',
    degreeAttributes: 'Humanities',
  },
  {
    year: 2025,
    term: 'Spring',
    yearTerm: '2025-sp',
    subject: 'PHIL',
    courseNumber: 250,
    courseId: 'PHIL250',
    section: '04',
    title: 'Logic',
    description: 'Logic. Covers foundational theory and practical techniques.',
    creditHours: '3-4',
    format: 'Seminar',
    meetingDays: 'M',
    startTime: '15:00',
    endTime: '16:50',
    location: 'Sage Hall 465',
    instructor: 'Jordan Patel',
    capacity: 40,
    enrolled: 9,
    status: 'Closed',
    degreeAttributes: 'Ethics',
  },
  {
    year: 2025,
    term: 'Fall',
    yearTerm: '2025-fa',
    subject: 'BIOL',
    courseNumber: 140,
    courseId: 'BIOL140',
    section: '04',
    title: 'Ecology',
    description:
      'Ecology. Covers foundational theory and practical techniques.',
    creditHours: '1',
    format: 'Lab',
    meetingDays: 'W',
    startTime: '11:00',
    endTime: '11:50',
    location: 'Phillips Hall 385',
    instructor: 'Jamie Martinez',
    capacity: 60,
    enrolled: 6,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'THEA',
    courseNumber: 550,
    courseId: 'THEA550',
    section: '04',
    title: 'Advanced Acting',
    description:
      'Advanced Acting. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '3-4',
    format: 'Lecture',
    meetingDays: 'W',
    startTime: '12:00',
    endTime: '13:50',
    location: 'Olin Library 171',
    instructor: 'Casey Smith',
    capacity: 40,
    enrolled: 31,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2025,
    term: 'Spring',
    yearTerm: '2025-sp',
    subject: 'STAT',
    courseNumber: 370,
    courseId: 'STAT370',
    section: '01',
    title: 'Statistical Computing',
    description:
      'Statistical Computing. Covers foundational theory and practical techniques.',
    creditHours: '2',
    format: 'Lab',
    meetingDays: 'MWF',
    startTime: '16:00',
    endTime: '17:15',
    location: 'Olin Library 255',
    instructor: 'Avery Brown',
    capacity: 45,
    enrolled: 39,
    status: 'Closed',
    degreeAttributes: 'Communication',
  },
  {
    year: 2025,
    term: 'Summer',
    yearTerm: '2025-su',
    subject: 'THEA',
    courseNumber: 240,
    courseId: 'THEA240',
    section: '03',
    title: 'Theatre History',
    description:
      'Theatre History. Covers foundational theory and practical techniques.',
    creditHours: '2',
    format: 'Hybrid',
    meetingDays: 'W',
    startTime: '16:30',
    endTime: '17:20',
    location: 'Goldwin Smith 249',
    instructor: 'Drew Clark',
    capacity: 75,
    enrolled: 73,
    status: 'Open',
    degreeAttributes: 'Ethics',
  },
  {
    year: 2025,
    term: 'Spring',
    yearTerm: '2025-sp',
    subject: 'CHEM',
    courseNumber: 530,
    courseId: 'CHEM530',
    section: '02',
    title: 'Organic Chemistry',
    description:
      'Organic Chemistry. Students complete a final project demonstrating key skills.',
    creditHours: '2',
    format: 'Hybrid',
    meetingDays: 'MWF',
    startTime: '16:30',
    endTime: '18:20',
    location: 'Statler Hall 444',
    instructor: 'Cameron Garcia',
    capacity: 40,
    enrolled: 15,
    status: 'Open',
    degreeAttributes: 'Ethics',
  },
  {
    year: 2025,
    term: 'Fall',
    yearTerm: '2025-fa',
    subject: 'LING',
    courseNumber: 570,
    courseId: 'LING570',
    section: '04',
    title: 'Sociolinguistics',
    description:
      'Sociolinguistics. Focuses on methods, tools, and ethical practice.',
    creditHours: '4',
    format: 'Hybrid',
    meetingDays: 'R',
    startTime: '09:30',
    endTime: '11:20',
    location: 'Hollister Hall 426',
    instructor: 'Jordan Patel',
    capacity: 35,
    enrolled: 22,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2026,
    term: 'Summer',
    yearTerm: '2026-su',
    subject: 'ARCH',
    courseNumber: 360,
    courseId: 'ARCH360',
    section: '01',
    title: 'Architectural Design',
    description:
      'Architectural Design. Includes case studies and small-group activities.',
    creditHours: '3',
    format: 'Lecture',
    meetingDays: 'M',
    startTime: '12:00',
    endTime: '13:15',
    location: 'Statler Hall 337',
    instructor: 'Rowan Anderson',
    capacity: 120,
    enrolled: 88,
    status: 'Open',
    degreeAttributes: 'Humanities',
  },
  {
    year: 2024,
    term: 'Spring',
    yearTerm: '2024-sp',
    subject: 'STAT',
    courseNumber: 110,
    courseId: 'STAT110',
    section: '02',
    title: 'Statistical Computing',
    description:
      'Statistical Computing. Students complete a final project demonstrating key skills.',
    creditHours: '3',
    format: 'Lab',
    meetingDays: 'W',
    startTime: '16:00',
    endTime: '17:50',
    location: 'Goldwin Smith 343',
    instructor: 'Jordan Lee',
    capacity: 75,
    enrolled: 40,
    status: 'Open',
    degreeAttributes: 'Humanities',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'CS',
    courseNumber: 310,
    courseId: 'CS310',
    section: '02',
    title: 'Human-Computer Interaction',
    description:
      'Human-Computer Interaction. Includes case studies and small-group activities.',
    creditHours: '1-3',
    format: 'Seminar',
    meetingDays: 'R',
    startTime: '11:00',
    endTime: '12:15',
    location: 'Statler Hall 336',
    instructor: 'Morgan Lewis',
    capacity: 60,
    enrolled: 40,
    status: 'Open',
    degreeAttributes: 'Ethics',
  },
  {
    year: 2024,
    term: 'Summer',
    yearTerm: '2024-su',
    subject: 'THEA',
    courseNumber: 270,
    courseId: 'THEA270',
    section: '04',
    title: 'Stagecraft',
    description:
      'Stagecraft. Includes case studies and small-group activities.',
    creditHours: '3-4',
    format: 'Lecture',
    meetingDays: 'MWF',
    startTime: '12:00',
    endTime: '13:15',
    location: 'Hollister Hall 152',
    instructor: 'Rowan Walker',
    capacity: 100,
    enrolled: 23,
    status: 'Open',
    degreeAttributes: 'Quantitative Reasoning',
  },
  {
    year: 2024,
    term: 'Spring',
    yearTerm: '2024-sp',
    subject: 'PHIL',
    courseNumber: 550,
    courseId: 'PHIL550',
    section: '04',
    title: 'Graduate Philosophy of Mind',
    description:
      'Graduate Philosophy of Mind. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '4',
    format: 'Lab',
    meetingDays: 'R',
    startTime: '11:30',
    endTime: '13:20',
    location: 'Morrill Hall 444',
    instructor: 'Taylor Johnson',
    capacity: 25,
    enrolled: 7,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2025,
    term: 'Summer',
    yearTerm: '2025-su',
    subject: 'MATH',
    courseNumber: 560,
    courseId: 'MATH560',
    section: '04',
    title: 'Advanced Differential Equations',
    description:
      'Advanced Differential Equations. Includes case studies and small-group activities.',
    creditHours: '4',
    format: 'Seminar',
    meetingDays: 'M',
    startTime: '11:00',
    endTime: '12:15',
    location: 'Olin Library 195',
    instructor: 'Riley Walker',
    capacity: 75,
    enrolled: 6,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2024,
    term: 'Fall',
    yearTerm: '2024-fa',
    subject: 'ARCH',
    courseNumber: 580,
    courseId: 'ARCH580',
    section: '04',
    title: 'Urban Planning',
    description:
      'Urban Planning. Focuses on methods, tools, and ethical practice.',
    creditHours: '4',
    format: 'Studio',
    meetingDays: 'MWF',
    startTime: '11:00',
    endTime: '12:50',
    location: 'Sage Hall 249',
    instructor: 'Avery Smith',
    capacity: 35,
    enrolled: 34,
    status: 'Open',
    degreeAttributes: 'Communication',
  },
  {
    year: 2026,
    term: 'Spring',
    yearTerm: '2026-sp',
    subject: 'EDUC',
    courseNumber: 510,
    courseId: 'EDUC510',
    section: '01',
    title: 'Curriculum Design',
    description:
      'Curriculum Design. Students complete a final project demonstrating key skills.',
    creditHours: '1-3',
    format: 'Lab',
    meetingDays: 'TR',
    startTime: '09:30',
    endTime: '11:20',
    location: 'Statler Hall 152',
    instructor: 'Drew Walker',
    capacity: 35,
    enrolled: 19,
    status: 'Open',
    degreeAttributes: 'Writing Intensive; Natural Science',
  },
  {
    year: 2024,
    term: 'Spring',
    yearTerm: '2024-sp',
    subject: 'CHEM',
    courseNumber: 230,
    courseId: 'CHEM230',
    section: '03',
    title: 'Physical Chemistry',
    description:
      'Physical Chemistry. Covers foundational theory and practical techniques.',
    creditHours: '1-3',
    format: 'Seminar',
    meetingDays: 'MWF',
    startTime: '11:00',
    endTime: '11:50',
    location: 'Hollister Hall 279',
    instructor: 'Jamie Smith',
    capacity: 120,
    enrolled: 68,
    status: 'Open',
    degreeAttributes: 'Writing Intensive',
  },
  {
    year: 2026,
    term: 'Spring',
    yearTerm: '2026-sp',
    subject: 'GEOG',
    courseNumber: 120,
    courseId: 'GEOG120',
    section: '04',
    title: 'Human Geography',
    description:
      'Human Geography. Includes case studies and small-group activities.',
    creditHours: '3-4',
    format: 'Lab',
    meetingDays: 'TR',
    startTime: '11:00',
    endTime: '11:50',
    location: 'Goldwin Smith 226',
    instructor: 'Rowan Walker',
    capacity: 60,
    enrolled: 31,
    status: 'Open',
    degreeAttributes: 'Ethics',
  },
  {
    year: 2025,
    term: 'Fall',
    yearTerm: '2025-fa',
    subject: 'BIOL',
    courseNumber: 480,
    courseId: 'BIOL480',
    section: '03',
    title: 'Ecology',
    description:
      'Ecology. Covers foundational theory and practical techniques.',
    creditHours: '3',
    format: 'Studio',
    meetingDays: 'W',
    startTime: '09:00',
    endTime: '10:50',
    location: 'Goldwin Smith 132',
    instructor: 'Rowan Martinez',
    capacity: 60,
    enrolled: 13,
    status: 'Closed',
    degreeAttributes: 'Communication',
  },
  {
    year: 2025,
    term: 'Spring',
    yearTerm: '2025-sp',
    subject: 'ECON',
    courseNumber: 590,
    courseId: 'ECON590',
    section: '02',
    title: 'Public Policy',
    description:
      'Public Policy. Students complete a final project demonstrating key skills.',
    creditHours: '1',
    format: 'Lecture',
    meetingDays: 'MWF',
    startTime: '10:30',
    endTime: '11:20',
    location: 'Olin Library 325',
    instructor: 'Cameron Nguyen',
    capacity: 60,
    enrolled: 12,
    status: 'Open',
    degreeAttributes: 'Natural Science',
  },
  {
    year: 2025,
    term: 'Fall',
    yearTerm: '2025-fa',
    subject: 'PSYC',
    courseNumber: 310,
    courseId: 'PSYC310',
    section: '03',
    title: 'Research Methods',
    description:
      'Research Methods. Focuses on methods, tools, and ethical practice.',
    creditHours: '2',
    format: 'Hybrid',
    meetingDays: 'M',
    startTime: '09:30',
    endTime: '11:20',
    location: 'Sage Hall 319',
    instructor: 'Parker Patel',
    capacity: 25,
    enrolled: 0,
    status: 'Open',
    degreeAttributes: 'Social Science; Communication',
  },
  {
    year: 2024,
    term: 'Summer',
    yearTerm: '2024-su',
    subject: 'LING',
    courseNumber: 100,
    courseId: 'LING100',
    section: '03',
    title: 'Phonetics',
    description:
      'Phonetics. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '3-4',
    format: 'Studio',
    meetingDays: 'TR',
    startTime: '11:30',
    endTime: '12:20',
    location: 'Statler Hall 145',
    instructor: 'Drew Lewis',
    capacity: 25,
    enrolled: 3,
    status: 'Open',
    degreeAttributes: 'Writing Intensive',
  },
  {
    year: 2025,
    term: 'Fall',
    yearTerm: '2025-fa',
    subject: 'MATH',
    courseNumber: 180,
    courseId: 'MATH180',
    section: '01',
    title: 'Differential Equations',
    description:
      'Differential Equations. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '2',
    format: 'Hybrid',
    meetingDays: 'TR',
    startTime: '16:30',
    endTime: '18:20',
    location: 'Olin Library 310',
    instructor: 'Skyler Anderson',
    capacity: 75,
    enrolled: 27,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2024,
    term: 'Summer',
    yearTerm: '2024-su',
    subject: 'ARCH',
    courseNumber: 360,
    courseId: 'ARCH360',
    section: '03',
    title: 'Architectural Design',
    description:
      'Architectural Design. Covers foundational theory and practical techniques.',
    creditHours: '3',
    format: 'Seminar',
    meetingDays: 'R',
    startTime: '10:00',
    endTime: '11:50',
    location: 'Hollister Hall 469',
    instructor: 'Skyler Smith',
    capacity: 20,
    enrolled: 9,
    status: 'Open',
    degreeAttributes: 'Ethics',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'PHYS',
    courseNumber: 460,
    courseId: 'PHYS460',
    section: '01',
    title: 'Electricity and Magnetism',
    description:
      'Electricity and Magnetism. Focuses on methods, tools, and ethical practice.',
    creditHours: '1',
    format: 'Online',
    meetingDays: 'TR',
    startTime: '09:30',
    endTime: '10:45',
    location: 'Statler Hall 391',
    instructor: 'Quinn Johnson',
    capacity: 100,
    enrolled: 87,
    status: 'Open',
    degreeAttributes: 'Social Science; Humanities',
  },
  {
    year: 2024,
    term: 'Fall',
    yearTerm: '2024-fa',
    subject: 'ENGL',
    courseNumber: 200,
    courseId: 'ENGL200',
    section: '01',
    title: 'Technical Writing',
    description:
      'Technical Writing. Covers foundational theory and practical techniques.',
    creditHours: '3',
    format: 'Online',
    meetingDays: 'W',
    startTime: '15:30',
    endTime: '17:20',
    location: 'Morrill Hall 427',
    instructor: 'Jamie Martinez',
    capacity: 120,
    enrolled: 19,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2024,
    term: 'Summer',
    yearTerm: '2024-su',
    subject: 'MUS',
    courseNumber: 280,
    courseId: 'MUS280',
    section: '03',
    title: 'Performance Workshop',
    description:
      'Performance Workshop. Covers foundational theory and practical techniques.',
    creditHours: '3-4',
    format: 'Online',
    meetingDays: 'W',
    startTime: '10:30',
    endTime: '12:20',
    location: 'Sage Hall 129',
    instructor: 'Morgan Patel',
    capacity: 60,
    enrolled: 7,
    status: 'Closed',
    degreeAttributes: '',
  },
  {
    year: 2026,
    term: 'Summer',
    yearTerm: '2026-su',
    subject: 'ART',
    courseNumber: 100,
    courseId: 'ART100',
    section: '02',
    title: 'Art History',
    description:
      'Art History. Covers foundational theory and practical techniques.',
    creditHours: '4',
    format: 'Seminar',
    meetingDays: 'M',
    startTime: '14:30',
    endTime: '15:20',
    location: 'Olin Library 483',
    instructor: 'Rowan Walker',
    capacity: 40,
    enrolled: 7,
    status: 'Open',
    degreeAttributes: 'Ethics',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'ENGL',
    courseNumber: 510,
    courseId: 'ENGL510',
    section: '04',
    title: 'Graduate Technical Writing',
    description:
      'Graduate Technical Writing. Students complete a final project demonstrating key skills.',
    creditHours: '2',
    format: 'Online',
    meetingDays: 'MWF',
    startTime: '14:00',
    endTime: '15:15',
    location: 'Hollister Hall 445',
    instructor: 'Drew Patel',
    capacity: 35,
    enrolled: 32,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2024,
    term: 'Fall',
    yearTerm: '2024-fa',
    subject: 'HIST',
    courseNumber: 450,
    courseId: 'HIST450',
    section: '04',
    title: 'Advanced Modern Europe',
    description:
      'Advanced Modern Europe. Focuses on methods, tools, and ethical practice.',
    creditHours: '1-3',
    format: 'Lecture',
    meetingDays: 'TR',
    startTime: '15:00',
    endTime: '16:15',
    location: 'Statler Hall 468',
    instructor: 'Riley Smith',
    capacity: 25,
    enrolled: 18,
    status: 'Open',
    degreeAttributes: '',
  },
  {
    year: 2026,
    term: 'Fall',
    yearTerm: '2026-fa',
    subject: 'ART',
    courseNumber: 280,
    courseId: 'ART280',
    section: '01',
    title: 'Photography',
    description:
      'Photography. Covers foundational theory and practical techniques.',
    creditHours: '4',
    format: 'Lecture',
    meetingDays: 'MWF',
    startTime: '13:30',
    endTime: '14:45',
    location: 'Tjaden Hall 333',
    instructor: 'Avery Johnson',
    capacity: 35,
    enrolled: 18,
    status: 'Open',
    degreeAttributes: 'Communication',
  },
  {
    year: 2026,
    term: 'Spring',
    yearTerm: '2026-sp',
    subject: 'MUS',
    courseNumber: 530,
    courseId: 'MUS530',
    section: '02',
    title: 'Graduate Music Theory',
    description:
      'Graduate Music Theory. Emphasizes critical reading, discussion, and applied projects.',
    creditHours: '3',
    format: 'Online',
    meetingDays: 'W',
    startTime: '09:30',
    endTime: '10:20',
    location: 'Uris Hall 153',
    instructor: 'Morgan Martinez',
    capacity: 35,
    enrolled: 26,
    status: 'Closed',
    degreeAttributes: '',
  },
  {
    year: 2026,
    term: 'Spring',
    yearTerm: '2026-sp',
    subject: 'BIOL',
    courseNumber: 130,
    courseId: 'BIOL130',
    section: '04',
    title: 'Ecology',
    description:
      'Ecology. Covers foundational theory and practical techniques.',
    creditHours: '3-4',
    format: 'Studio',
    meetingDays: 'TR',
    startTime: '10:00',
    endTime: '11:50',
    location: 'Statler Hall 138',
    instructor: 'Skyler Wilson',
    capacity: 20,
    enrolled: 13,
    status: 'Open',
    degreeAttributes: 'Writing Intensive',
  },
] as const;
