/* istanbul ignore file */
/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-charts' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    'chart.canvas.role_description': { message: 'chart' },
    'chart.focus_element.multi_series.description': {
      message: '{0}, series {1} of {2}. {3}: {4}. Point {5} of {6}.',
    },
    'chart.focus_element.single_series.description': {
      message: '{0}: {1}. Point {2} of {3}.',
    },
    'chart.legend.list_label': { message: 'Chart legend' },
    'chart.menu.view_data_table': { message: 'View data table' },
    'chart_data_grid.category_column_name': { message: 'Category' },
    'chart_data_grid.close_button': { message: 'Close' },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyChartsResourcesModule {}
