/* istanbul ignore file */
/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module lib/modules/shared/sky-charts' schematic.
 * To update this file, simply rerun the command.
 */
import { NgModule } from '@angular/core';
import {
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesService,
} from '@skyux/i18n';

const RESOURCES: Record<string, SkyLibResources> = {
  'EN-US': {
    'chart.canvas.role_description': { message: 'chart' },
    'chart.canvas.label.bar': { message: 'Bar chart' },
    'chart.canvas.label.line': { message: 'Line chart' },
    'chart.canvas.label.donut': { message: 'Donut chart' },
    'chart.focus_element.multi_series.description': {
      message: '{0}, series {1} of {2}. {3}: {4}. Point {5} of {6}.',
    },
    'chart.focus_element.single_series.description': {
      message: '{0}: {1}. Point {2} of {3}.',
    },
    'chart.legend.aria_label': { message: 'Chart legend' },
    'chart.legend.legend_item.aria_description': {
      message: 'Press Space or Enter to toggle inclusion in chart.',
    },
    'chart.legend.legend_item.aria_label': {
      message: '{0}, Legend item {1} of {2}',
    },
    'chart.menu.label': {
      message: 'Context menu for {0}',
    },
    'chart.menu.view_data_table': { message: 'View data table' },
    'chart.menu.view_data_table.aria_label': {
      message: 'View data table for {0}',
    },
    'chart_data_grid.category_column_name': { message: 'Category' },
    'chart_data_grid.close_button': { message: 'Close' },
    'chart.summary.bar_chart': {
      message: 'Bar chart with {0} data series.',
    },
    'chart.summary.line_chart': {
      message: 'Line chart with {0} data series.',
    },
    'chart.summary.donut_chart': {
      message: 'Donut chart with {0} data points.',
    },
    'chart.summary.category_axis': {
      message: 'The chart has a category axis displaying {0}.',
    },
    'chart.summary.measure_axis': {
      message: 'The chart has a measure axis displaying {0}.',
    },
  },
};

SkyLibResourcesService.addResources(RESOURCES);

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
})
export class SkyChartsResourcesModule {}
